### PR TITLE
New sonar options

### PR DESCRIPTION
**Pull request by Slesa**
Added missing parameters /d and /s to the SonarQube parameters.

### CODE REVIEW

**Comment by philipooo** [comment]
This already looks very good!

But am I right saying it's currently not possible to pass the corresponding values for the parameters?
e.g. `Settings = [("sonar.debug",True);("sonar.login","qwe34234iqeri")]`

There is one use-case that is not yet covered by this solution: We (company) are not storing the credentials in our SonarQube.Analytics.xml, instead we are passing them directly to the command line by our buildserver. Since the analyser does not store the credentials in the filesystem the execution of `end` fails because of the lack of the credentials. We have to pass `sonar.login` (and optionally `sonar.password`, if someone is not using tokens) again to the call of `end`.

A solution could be to add an additional value to the tuples in the settings-property like:
`Settings = [("sonar.debug",True,Begin);("sonar.login","qwe34234iqeri",BeginEnd)]`

Cheers

**Comment by Slesa** [comment]
Probably the settings currently have to be `Settings = [("sonar.debug=True");("sonar.login=qwe34234iqeri")]`. Should I add a second field EndSettings? Tuples in settings is a bit uncomfortable, isn't it?

**Comment by forki** [comment]
thanks

**Comment by philipooo** [comment]
Ok, of course its possible to add the value directly to the list, but the sample does not show this.
https://github.com/fsharp/FAKE/pull/1172/files#diff-83519ec9f82c298670e2d0087edf4c98R59

A second field EndSettings would be totaly fine for me.

**Pull request merged**
