### PR TITLE
URGENT: Correct publish artifact

### PR DESCRIPTION
**Pull request by BlythMeister**
image

### CODE REVIEW

**Comment by matthid** [comment]
Now you know why I'm so hesitant to accept prs around this area, problem is we have ne easy way to test this stuff...

**Comment by BlythMeister** [comment]
Yeah, true story!

**Comment by matthid** [comment]
any idea how to catch errors like this before production are welcome. feel free to add integration tests, note that release/next branch runs on TeamCity as we have a sponsored ci..

**Comment by BlythMeister** [comment]
Not really sure, I only noticed because my files were not in TeamCity...not sure how to script that check.

**Comment by matthid** [comment]
While it is red it looks reasonably simple...

**Comment by matthid** [comment]
Thanks!

**Pull request merged**
