### PR TITLE
Next Release

### PR DESCRIPTION
**Pull request by matthid**

### CODE REVIEW

**Comment by matthid** [comment]
@kblohm  It seems like something broke with the fake-template on AppVeyor as the builds in https://github.com/fsharp/FAKE/pull/2002 https://github.com/fsharp/FAKE/pull/2008 and https://github.com/fsharp/FAKE/pull/2021 went red :/ Could you please take a look? I hope this doesn't impact new users.

**Comment by kblohm** [comment]
@matthid The template is working fine. The tests are broken. Probably since the update to the `DotNet-Module` that changed how the `cli-version` is resolved.
As far as i can tell this is what happens:
The tests use `DotNet.exec` to install the `fake-template`. That uses 2.1.300 because of the `global.json`. The tests then run in a temp-directory with (probably) 2.1.302 because that is the latest version. But the template is not installed for that version ;).

At least that is how i could reproduce it locally. Not sure why that only happens on AppVeyor. Maybe the latest version is not installed on everything else.

**Comment by matthid** [comment]
I think I'm waiting with this for https://github.com/fsprojects/Paket/pull/3307, which fixes https://github.com/fsharp/FAKE/issues/2029 and https://github.com/fsharp/FAKE/pull/1987#issuecomment-406845966

In particular the first PR fixes some fake5-scenarios which worked previously.

**Comment by matthid** [comment]
Also I think we should have a fix for https://github.com/fsharp/FAKE/issues/2025 in the next release as well.

**Pull request merged**
