### PR TITLE
Feature/#1177 docfx helper

### PR DESCRIPTION
**Pull request by shortsn**
Hi, this adds a Helper for DocFx (requested in #1177).
It works like a charm in combination with the [DocFx Commandline Package](https://www.nuget.org/packages/docfx.msbuild/) as build dependency.

### CODE REVIEW

**Comment by forki** [comment]
can you please push a zero diff commit to trigger the build again? thx.

**Comment by shortsn** [comment]
@forki -> done

**Comment by forki** [comment]
awesome. thanks

**Comment by forki** [comment]
I removed the autoopen, because we don't want to create new modules with that

**Comment by shortsn** [comment]
Ah ok, good to know.

**Comment by bentayloruk** [comment]
@shortsn just adding a note for others that end up here.  The DocFx package you linked to has been unlisted.  I *think* the replacement is [docfx.console](https://www.nuget.org/packages/docfx.console/).  Works for me anyway, thanks!

**Comment by shortsn** [comment]
@bentayloruk, you're right. Thanks for this addition.

**Pull request merged**
