### PR TITLE
Added CommandLineHelper that deals with parsing command line parametters

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Named the functions so that they were obviously different from EnvironmentHelper.

### CODE REVIEW

**Comment by forki** [comment]
Why can't you use https://github.com/nessos/UnionArgParser we already have a dependency on it

**Comment by voiceofwisdom** [comment]
I could use that, I liked the way getBuildParam worked for environment variables. Much simpler than creating a Union. I dont see a way to do that with UnionArgParser.

**Comment by matthid** [comment]
I think we can make a new FAKE 5 module out of this which can have any dependency needed. Would you be interested to update this?

**Comment by xavierzwirtz** [comment]
Sure, point me in the right direction and I will get it updated.

**Comment by matthid** [comment]
Basically you create a nuget package with netstandard 1.6 support. If you want to maintain it just create your own repository and we can advertise it here on the fake website. Or you just add a new project in the src/app/ directory (easiest is to copy one of the existing folders and rename stuff). the Build will tell you if something went wrong and if you need help let me know.

everyone can decide to use the module and its dependency or not by adding the module to the dependencies file or not (see fake 5 docs).

**Comment by matthid** [comment]
Closing this due to inactivity. Please consider contributing this as FAKE 5 module! Thanks for your work on FAKE and sorry for the HUGE delay :(

Please let me know if you need help porting this to netcore.

**Pull request closed without merging**
