### PR TITLE
Issue 1342: NugetHelper.fs: GetPackageVersion

### PR DESCRIPTION
**Pull request by bobahml**
It seems that in order to solve the problem enough to add a point to the search pattern.

### CODE REVIEW

**Comment by forki** [comment]
That would not help with castle and castle.core right?

**Comment by bobahml** [comment]
In the console, I see now:
Version 3.3.3 found for package Castle.Core

**Comment by forki** [comment]
And for caste?

**Comment by bobahml** [comment]
//    Castle.Windsor-NLog.3.3.0
//    Castle.Windsor.3.3.0
 
Also it works ->
Version 3.3.0 found for package Castle.Windsor

**Comment by forki** [comment]
Cool.

**Pull request merged**
