### PR TITLE
Fix IgnoreTestCase

### PR DESCRIPTION
**Pull request by laedit**
use the Ignored param as stated in AppVeyor docs: http://www.appveyor.com/docs/build-worker-api#update-tests

### CODE REVIEW

**Comment by forki** [comment]
what about the message param?

**Comment by laedit** [comment]
It wasn't used and have no proper usage in the AppVeyor docs so I assumed that it wasn't necessary.

**Comment by forki** [comment]
yes but this now broke the signature of the function. Which is probably OK in this case, but it also broke the build.

**Comment by laedit** [comment]
Sorry, I was too quick.

If you are ok with the suppression of the `message` param I will fix the build, otherwise I will restore it.

**Comment by forki** [comment]
I suggest you add it again. even if it doesn't do anything useful.

**Comment by laedit** [comment]
Done, sorry for the disturbance.

**Comment by forki** [comment]
thx

**Pull request merged**
