### PR TITLE
Updates paket to 6.0.0-alpha022 to support netcoreapp5.0

### LINKED ISSUE #2496: Working with netcoreapp5.0/paket 6.0 preview
### Description

Please provide a succinct description of your issue.

I'm playing with the [F# 5 preview](https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/) which requires `netcoreapp5.0`. [Paket 6.0](https://github.com/fsprojects/Paket/blob/8543378407ebc727ac799ff9f9113d7b8d288ef4/RELEASE_NOTES.md#600-alpha022---2020-03-27) seems to support this but when I run FAKE I get:

```
There was a problem while setting up the environment:
-> Error during parsing of '/Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/paket.lock'.
   StackTrace:
        at Paket.LockFile.Parse(String lockFileName, String[] lines)
        at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
        at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
        at System.Lazy`1.CreateValue()
        at Fake.Runtime.FakeRuntime.retrieveInfosUncached@141(String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, Lazy`1 lockFile, Lazy`1 cache, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 142
        at Fake.Runtime.FakeRuntime.getKnownDependencies@337-1.Invoke(Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 337
        at Fake.Runtime.CoreCache.getCached[a](FSharpFunc`2 getUncached, FSharpFunc`2 readFromCache, FSharpFunc`2 writeToCache, FSharpFunc`2 checkCacheUpToDate) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 41
        at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
        at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
        at System.Lazy`1.CreateValue()
        at Fake.Runtime.FakeRuntime.paketCachingProvider@354-5.Fake-Runtime-CoreCache-ICachingProvider-TryLoadCache(FakeContext context) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 361
        at Fake.Runtime.CoreCache.prepareContext(FakeConfig config, ICachingProvider cache) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 482
        at Fake.Runtime.CoreCache.runScriptWithCacheProviderExt(FakeConfig config, ICachingProvider cache) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 508
        at Program.runOrBuild(RunArguments args) in D:\a\1\s\src\app\Fake.netcore\Program.fs:line 156
-> invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0) (< netstandard1.2)) (&& (>= netcoreapp5.0) (< netstandard1.3)) (&& (>= netcoreapp5.0) (< netstandard1.4)) (&& (>= netcoreapp5.0) (< netstandard1.5)) (&& (>= netcoreapp5.0) (< netstandard2.0)) (&& (< netstandard1.0) (>= netstandard1.6) (< portable-net45+win8)) (&& (< netstandard1.0) (>= netstandard1.6) (>= win8)) (&& (< netstandard1.0) (>= netstandard1.6) (< win8)) (&& (< netstandard1.3) (>= netstandard1.6) (< win8) (>= wpa81)) (&& (< netstandard1.5) (>= netstandard1.6) (>= uap10.0)) (&& (>= netstandard1.6) (< portable-net45+win8+wpa81)) (&& (>= netstandard1.6) (>= uap10.1)) (&& (>= netstandard1.6) (>= wp8))'
   StackTrace:
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
        at Paket.Requirements.parseOperand@828(Boolean skipSimplify, List`1 problems, String text, FSharpList`1 cur, String next)
        at Paket.Requirements.parseOperator@768(Boolean skipSimplify, List`1 problems, String text)
        at Paket.Requirements.parseOperand@828(Boolean skipSimplify, List`1 problems, String text, FSharpList`1 cur, String next)
        at Paket.Requirements.parseOperator@768(Boolean skipSimplify, List`1 problems, String text)
        at Paket.Requirements.parseRestrictionsRaw(Boolean skipSimplify, String text)
        at Paket.Requirements.InstallSettings.Parse(Boolean isSimplified, String text)
        at Paket.LockFileParser.parsePackage@423-1(String s)
        at Paket.LockFileParser.Parse$cont@483-3(FSharpFunc`2 removeBrackets, FSharpList`1 otherGroups, ParseState currentGroup, String details, FSharpOption`1 matchValue, Unit unitVar)
        at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 729
        at Paket.LockFile.Parse(String lockFileName, String[] lines)
```

Is there a way to teach FAKE to use a prerelease version of paket?

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a `netcoreapp5.0` project.
2. setup paket 6.0 preview
3. install fake
4. run fake

or pull https://github.com/TheAngryByrd/FsToolkit.ErrorHandling/tree/applicative-support and run `build.sh/cmd`

### Expected behavior

Can teach FAKE's to use a preview of paket so it parse the paket.lock file.

### Actual behavior

FAKE's use of paket can parse the paket.lock file

### Known workarounds

None

### Related information 

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20176.6
 Commit:    d752c3e07b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.2.20176.6/

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1

.NET Core SDKs installed:
  1.0.0-preview2.1-003155 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003121 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003131 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003156 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  1.0.0-preview4-004233 [/usr/local/share/dotnet/sdk]
  1.0.0-rc4-004711 [/usr/local/share/dotnet/sdk]
  1.0.0-rc4-004771 [/usr/local/share/dotnet/sdk]
  1.0.1 [/usr/local/share/dotnet/sdk]
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.3 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.603 [/usr/local/share/dotnet/sdk]
  2.1.802 [/usr/local/share/dotnet/sdk]
  2.2.102 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]
  3.0.100-preview7-012821 [/usr/local/share/dotnet/sdk]
  3.0.100-preview8-013656 [/usr/local/share/dotnet/sdk]
  3.0.100-preview9-014004 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.2.20176.6 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0-preview1-001100-00 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

- dotnet core 5.0.100-preview.2.20176.6
-  fake-cli: 5.18.3
- paket 6.0.0-alpha022

### PR DESCRIPTION
**Pull request by TheAngryByrd**
### Description

Updates paket in the netcorerunner group to 6.0.0-alpha022 to support netcoreapp5.0.

If available, link to an existing issue this PR fixes. For example:

- fixes #2496 

## TODO

Feel free to open the PR and ask for help

- [ ] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [ ] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [ ] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [ ] (if new module) the module is in the correct namespace
- [ ] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [ ] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by matthid** [comment]
@forki is this fix contained in the latest 5 "stable" release as well? Do we need to use the alpha here to get netcoreapp5 support?

**Comment by matthid** [comment]
@TheAngryByrd Sorry this conflicted with another PR and will probably conflict again with #2500. Lets first figure out with version to use.
I'm not too worried about using an alpha here, but people still using stable Paket versions locally will get a warning of a version mismatch between FAKE and Paket.

**Comment by TheAngryByrd** [comment]
Just want me to rebase this or is there something else I should do?

**Comment by fc1943s** [comment]
Any updates on this?

**Comment by matthid** [comment]
@fc1943s Yes I'm updating to latest paket.core right now but I'm running in a bunch of dependency problems :(

**Comment by matthid** [comment]
Can you test if `5.20.0-alpha.1580` solves the problem?

**Comment by fc1943s** [comment]
With the `framework: netcoreapp5.0` restriction in `paket.dependencies` I get the following error:

image

Removing the restriction, the complaint goes from `== netcoreapp5.0` to `>= netcoreapp5.0`.
It seems the parsing breaks at the first `netcoreapp5.0` occurrence in the `paket.lock` file.

**Comment by matthid** [comment]
Apparently this is not yet supported in the latest stable paket release:
```
E:\Projects\FAKE\test\fake-template\zkfc10k2.ind>dotnet paket install
Paket version 5.244.2
Performance:
 - Runtime: 158 milliseconds
Paket failed with
-> Error in paket.dependencies line 3
     Could not parse framework 'netcoreapp5.0'. Try to update or install again or report a paket bug.
```

So I guess you should report this to [Paket](https://github.com/fsprojects/Paket) (/cc @forki)

**Comment by TheAngryByrd** [comment]
@matthid 

Seems like the `fake-cli` didn't get updated. (or maybe it's reporting bad info?)

```
dotnet fake --version
FAKE 5 - F# Make (5.20.0-alpha.1580+vsts.2f8b467cf7cc4a5639b2273b2fd60c9e93d0da9c) (this line is written to standard error, see https://github.com/fsharp/FAKE/issues/2066)
FakePath: /Users/jimmybyrd/.nuget/packages/fake-cli/5.20.0-alpha.1580/tools/netcoreapp2.1/any/Fake.Runtime.dll
Paket.Core: 5.244.2
```

**Comment by matthid** [comment]
@TheAngryByrd No `5.244.2` was the latest a couple of hours ago. I asked @forki and he was kind enough to release a stable with support for this. So thanks to him the next alpha might work :)

**Comment by matthid** [comment]
@TheAngryByrd @fc1943s  Now with `5.245.1` and fake `5.20.0-alpha.1584` it should work, please try again

**Comment by TheAngryByrd** [comment]
works! 🎸 Thanks a ton!

**Comment by matthid** [comment]
Manually updated, anyway thanks for the PR to see the build

**Comment by fc1943s** [comment]
Worked for me too! Thanks guys
I guess updating to Paket 6 would hang the version for some time. Nice to have both stable versions with netcoreapp5.0 support (oh boy, net5.0 here it comes 😂)

**Pull request closed without merging**
