### PR TITLE
Pass OutputDataReceived to logfn instead of trace

### PR DESCRIPTION
**Pull request by koenmetsu**

### CODE REVIEW

**Comment by forki** [comment]
thx

**Comment by inosik** [comment]
Seems like this broke the build.

**Comment by koenmetsu** [comment]
Sorry about that, should be logfn with a format or just log, not sure which one is better. I'm not in a position to test this until tomorrow morning CEST, so feel free to revert or fix if urgent.

**Comment by inosik** [comment]
Actually I was about doing something else, but this change didn't let me compile. I reverted it for now in my local repo, but it isn't urgent, so I can wait.

**Comment by forki** [comment]
Will fix tomorrow

**Comment by koenmetsu** [comment]
Fixed in https://github.com/fsharp/FAKE/pull/907

**Pull request merged**
