### PR TITLE
Commit message will come for old and new git version

### PR DESCRIPTION
**Pull request by kunjee17**
I have updated code so it will work for old and new git versions. Code can be more refactored but I try to do with minimum changes. Have a look and let me know. 

PS: sorry for delay.

### CODE REVIEW

**Comment by forki** [comment]
LGTM

**Comment by kunjee17** [comment]
:+1:

**Comment by inosik** [comment]
`+ "\\COMMITMESSAGE"`doesn't work on non-Windows.

**Comment by forki** [comment]
Please send a pull request

**Pull request merged**
