### PR TITLE
Release 5.3.1

### PR DESCRIPTION
**Pull request by matthid**

### CODE REVIEW

**Comment by matthid** [comment]
image

SemVer is missing

**Comment by kblohm** [comment]
My first idea was also to change the version inside the script, but i dont think it needed unless you want to always install pre-releases.
I just tested installing the global tool without the `--version` parameter and that does install 5.3.0.
You can not leave the version blank for the `DotNetCliToolReference`, but as far as i can tell, using a * here also resolves to 5.3.0.

**Comment by matthid** [comment]
> * here also resolves to 5.3.0.

apparently `*` resolves to 5.0.0 as well... what a mess. What is wildcard even good for...

**Comment by kblohm** [comment]
Are you sure it does? 
If i specify `<DotNetCliToolReference Include="dotnet-fake" Version="5.0.0" />` and then run
```bash
dotnet fake --version
```
in that folder, i get a 5.0.0.
If i change that to * i get 5.3.0.

**Comment by matthid** [comment]
@kblohm I meant `dotnet tool install --version *`, yes `CliToolReference` seems to behave kind of reasonable

**Comment by kblohm** [comment]
For the global tool, just do not specify a --version at all. Thats what i meant for the global one.

**Comment by kblohm** [comment]
Also very nice that both of these behave differently xD

**Comment by matthid** [comment]
Welcome to the world of nuget.

Yes my "fix" is still kind of broken, if we want to install latest....

**Comment by kblohm** [comment]
If you want, i can change the template to only add the version when it is specified and use 
`<DotNetCliToolReference Include="dotnet-fake" Version="*" />` / not add the --version otherwise.

**Comment by matthid** [comment]
I'm not really familiar with the template thing and how to switch between given and not-given version flag. Additionally, `CliToolReference` is basically obsolete already

**Pull request merged**
