### PR TITLE
Change how npm.cmd is located in NpmHelper [hotfix_fake4]

### PR DESCRIPTION
**Pull request by nikolaia**
I've noticed that Yarn adds nodejs\bin to the path variable, which in the old code could return a folder that did not contain the npm.cmd file. I fixed this and also removed the fallback to the npm.js package, as it is silly to assume where the package directory is. If people are using that package they should overwrite the NpmFilePath variable.

This is the same as #1629 just against the `hotfix_fake4` branch

### CODE REVIEW

**Comment by matthid** [comment]
Is this a hotfix?

Note that the fallback to `"./packages/Npm.js/tools/npm.cmd"` assumes that one uses the https://www.nuget.org/packages/Npm.js package in combination with Paket. 
It looks a bit outdated?

**Comment by nikolaia** [comment]
The old way was a bit naive and broke in a lot of situation, the most noticeable one being that it would fail if you have a value containing `nodejs` in your PATH env variable that didn't contain `npm.cmd`. An example of that could be `C:\Program FIles\nodejs\bin` - while npm.cmd is located in `C:\Program FIles\nodejs` that comes later in your PATH env var.

The fallback to the package, as you say, assumes that you actuallyt use the package together with Paket. The package seems outdated and it just makes for an unclear error message.

**Comment by nikolaia** [comment]
Did you not consider this to be a hotfix for FAKE4? The dependency on/fallback to the outdated Npm.js nuget package can probably be considered broken, and this PR changes it to look more thorough trough the PATH variable for `npm.exe`. Basically same behaviour as on *nix where it assumes you install NPM yourself.

**Comment by nikolaia** [comment]
Solved for FAKE5 in https://github.com/fsharp/FAKE/pull/1822

**Comment by matthid** [comment]
>Did you not consider this to be a hotfix for FAKE4? 

Problem is that I cannot release fake 4 for some reason. Also at this time I don't think there is a good reason to stay on fake 4 anymore. The first step of the migration to fake 5 (upgrading the nuget package to v5) should be non-breaking.

**Pull request closed without merging**
