### PR TITLE
Append the content headers so the header `Content-Type` is included in the headers list

### LINKED ISSUE #2124: NuGet.Version.getLastNuGetVersion fails to parse response
### Description

NuGet.Version.getLastNuGetVersion fails to parse the response when using a myget feed.

### Repro steps

Call NuGet.Version.getLastNuGetVersion with a package on a myget feed

### Expected behavior

Call should return the SemVerInfo of the latest version of the package

### Actual behavior

The call causes an error:

```
-> BuildFailedException: Target 'PushPackages' failed.
   StackTrace:
        at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 654
        at Fake.Core.TargetModule.runOrDefaultWithArguments@840.Invoke(Boolean singleTarget, Int32 parallelJobs, FSharpList`1 arguments) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 841
        at Fake.Core.TargetModule.runWithDefault$cont@795-1(Boolean allowArgs, FSharpFunc`2 fDefault, FSharpMap`2 results, Unit unitVar) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 827
        at <StartupCode$Build_DEB2AE5EDD32A4D859D2F0179426F1C047BBF8A3AD6B26CA8391A476A1C5DFBF>.$Build$fsx.main@() in D:\<snip>\build\Build.fsx:line 194
-> One or more errors occurred. (Data at the root level is invalid. Line 1, position 1.)
-> XmlException: Data at the root level is invalid. Line 1, position 1.
   StackTrace:
        at System.Xml.XmlTextReaderImpl.Throw(Exception e)
        at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
        at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
        at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
        at System.Xml.XmlTextReaderImpl.Read()
        at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
        at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
        at Fake.DotNet.NuGet.Version.getLastNuGetVersion(String server, String packageName) in D:\a\1\s\src\app\Fake.DotNet.NuGet\NuGetVersion.fs:line 68
        at Build.clo@137-26.Invoke(Unit unitVar) in D:\<snip>\build\Build.fsx:line 143
        at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
        at Build.clo@119-21.Invoke(TargetParameter _arg9) in D:\<snip>\build\Build.fsx:line 131
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 196
```

It would seem that it is trying to parse the response as xml where myget is returning json (I have verified this with fiddler). It seems that myget is returning the `Content-Type` header as `application/json;odata=verbose;charset=utf-8` where the code looks to be checking for exactly `application/json` (https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.DotNet.NuGet/NuGetVersion.fs#L59 line 59) since this doesn't match it assumes it's xml.

### Known workarounds

None that I know of. I am migrating from Fake v4 so this is blocking my script from working.

### Related information 

* Operating system
Windows 10
* Branch
Stable
* .NET Runtime, CoreCLR or Mono Version
DotNetCore 2.1.402
* Version of FAKE (4.X, 5.X)
5.7.2 of Fake.DotNet.NuGet module

### PR DESCRIPTION
**Pull request by TangoMikeOscar**
Fixes #2124

I'm not an expert with f# but it seems a simple fix and I have tested this in isolation and it fixes the bug mentioned in the other issue.

Hopefully this is ok.

### CODE REVIEW

**Comment by TangoMikeOscar** [comment]
Unfortunately writing tests is a bit beyond my f# capabilities, wouldn't know where to start, only really learnt enough to get Fake working with our projects. Hopefully that is not a problem.

**Comment by matthid** [comment]
Ok I'll try to come up with a test, but it will take a couple of days

**Comment by matthid** [comment]
Yes, I just want to ensure we don't regress on this before merging

**Comment by matthid** [comment]
Thanks again for figuring out the root cause and providing a fix, I could reproduce with a test and refactored the code a bit (feel free to review)

**Pull request merged**
