### PR TITLE
New Signtool module

### PR DESCRIPTION
**Pull request by jimfoye**
New Signtool module replaces SigntoolHelper, FAKE 5 ready

### CODE REVIEW

**Comment by matthid** [comment]
Nice, thanks.
Note that the actual FAKE 5 module is still missing. I can do that work but than the PR will stay open for a while. The docs to create a new module are [here](https://github.com/fsharp/FAKE/blob/master/help/markdown/contributing.md#porting-a-module-to-fake-5).

I restarted the build as there was some temporary AppVeyor problem.

**Comment by jimfoye** [comment]
I did mark the old module as obsolete, but I see there are other things to do. I'm not currently building with .NET core. Yeah, if you don't mind, I think I'll leave the rest of this to you.

**Comment by matthid** [comment]
I just reviewed this again and have one question: Is there a reason to not use the regular form of how we specify parameters in FAKE (ie with a record and a callback function)?

**Comment by jimfoye** [comment]
I was just following the existing SignToolHelper example.

**Comment by matthid** [comment]
We now have lots of modules to see how it works. Basically all this needs is moving the file into it's own folder, adding a project file and setting up everything. Leaving this open for now. (Apparently I'm not finding the time to do it properly)

**Comment by matthid** [comment]
Closing for now, please feel free to send an updated PR for this. I'm just unable to find the time and I'd like to keep the PR and issue list clean. I hope everything is now a bit better documented as it was back then.

**Pull request closed without merging**
