### PR TITLE
Fake.Core.Context.setScriptContext function

### PR DESCRIPTION
**Pull request by vilinski**
### Description

Adds `Fake.Core.Context.setScriptContext` function, in short packed the code from comment https://github.com/fsharp/FAKE/issues/2517#issuecomment-727282959 as a single function:

## TODO

Feel free to open the PR and ask for help

- [x] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [ ] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [ ] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [ ] (if new module) the module is in the correct namespace
- [ ] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [ ] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by vilinski** [comment]
is something missing in this PR or it's just a maintainer who misses hist free time? :)

**Comment by matthid** [comment]
@vilinski It is the second one ;)
But other than that, the "problem" with this approach is when you use other `fsi` arguments like `fsi --define TEST myscript.fsx <other args>`. It is more a hack ;)

**Comment by vilinski** [comment]
is it different to `TEST=true dotnet fsi myscript.fsx <other args>` ?

can it be improved or generally not acceptable?

**Comment by matthid** [comment]
Well the easiest would be to not try to solve this problem and leave it to the user to supply the list of arguments. Iirc they even is an API to get script parameters which is usable from an fsx script.

**Pull request closed without merging**
