### PR TITLE
Added curl parameters ConnectTimeout and MaxTime and changed upload host.

### PR DESCRIPTION
**Pull request by molinch**
On our side we have a very slow network and all HockeyApp upload were failing in time-out.

So I added curl parameters ConnectTimeout and MaxTime. I also changed upload host to be upload.hockeyapp.net since it leads to faster uploads. You can see: http://support.hockeyapp.net/discussions/problems/33355-is-uploadhockeyappnet-available-for-general-use
Since we POST data we don't care about anything that could be cached by CloudFare.

### CODE REVIEW

**Comment by molinch** [comment]
Shell Exec now also takes into consideration the MaxTime parameter.

**Comment by molinch** [comment]
Is any extra info needed? Could we have some news?

**Comment by forki** [comment]
Did you look into the build errors?

**Comment by molinch** [comment]
@forki  It complains about `AppVeyor was unable to build non-mergeable pull request` therefore for me it's not very clear what should be done

**Comment by forki** [comment]
Also why don't you make the two parameters a timespan? This makes it easier for users to reference seconds vs minutes

**Comment by forki** [comment]
Ok ignore the build errors

**Comment by molinch** [comment]
I will use a TimeSpan then and add this commit

**Comment by forki** [comment]
cool. just let me know when it's ready

**Comment by forki** [comment]
ping

**Comment by matthid** [comment]
Closing this due to inactivity. Please consider contributing this again!

**Pull request closed without merging**
