### PR TITLE
Release 5.8.4

### PR DESCRIPTION
**Pull request by matthid**
* ~~NEW: Fake.Sql.SqlServer module - https://github.com/fsharp/FAKE/pull/2074~~
* ENHANCEMENT: Some modules are now usable without FAKE context (ie. in your regular projects)
* ENHANCEMENT: Inform when the `target` environment variable is used - https://github.com/fsharp/FAKE/issues/2107
* ENHANCEMENT: Improve TeamCity support - https://github.com/fsharp/FAKE/pull/2111
* ENHANCEMENT: Update Netstandard.Library package to `2.0.3` - https://github.com/fsharp/FAKE/pull/2106
* BUGFIX: Environment variables are case insensitive on windows, fake will now throw exceptions if it detects invalid environment maps
* BUGFIX: MSBuild properties containing special characters lead to errors - https://github.com/fsharp/FAKE/issues/2112
* BUGFIX: Improve error message when release notes are invalid - https://github.com/fsharp/FAKE/issues/2085
* BUGFIX: Improve error message when globbing pattern is invalid - https://github.com/fsharp/FAKE/issues/2073
* BUGFIX: Do no longer provide the `--parallel` argument by default when running expecto - https://github.com/fsharp/FAKE/issues/2039
* DOCS: Fix syntax errors in dacpac docs - https://github.com/fsharp/FAKE/pull/2115

### CODE REVIEW

**Comment by BlythMeister** [comment]
@matthid any eta on this version? and maybe inclusion of #2114 ?

**Comment by BlythMeister** [comment]
I would say show stopper when i've tried to use the new SQL Server module...linked to #2007

The module itself won't work as it can't get sni

**Comment by matthid** [comment]
@BlythMeister what do you mean?

**Comment by matthid** [comment]
Then I guess I’ll uncomment the sql module and not release it until we have a solution?
We need to have a runtime solution for this ‘additional-deps’ doesn’t help.

I’m pretty sure we have all the logic we need to find the dlls but we need to know which apis we need to call to load them

**Comment by BlythMeister** [comment]
Yes, I think that's best.  Maybe worth double checking it's not just me too 😂

**Pull request merged**
