### PR TITLE
Fixed DocFx bug

### LINKED ISSUE #2187: Illegal Characters in Path error when using DocFx
### Description
When running DocFx targets from within FAKE, the execution breaks due to an illegal characters in path exception.
It was working previously and I did not change anything since the last successful runs, maybe a FAKE update broke it?

The error thrown is:
`
> "C:\Git\FAKE-DocFx-Issue\packages\docfx.console\tools\docfx.exe" metadata "docs\docfx.json" "--output=\"\"" "--filter=\"\"" "--globalNamespaceId=\"\"" "--property=\"\"" "--log=\"\"" "--repositoryRoot=\"\"" "--correlationId=\"\"" (In: false, Out: false, Err: false)
[18-11-05 10:53:43.241]Error:System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.InternalGetDirectoryName(String path)
   bei Microsoft.DocAsCode.Common.ReportLogListener..ctor(String reportPath, String repoRoot, String root)
   bei Microsoft.DocAsCode.SubCommands.CommandCreator`2.Create(String[] args, ISubCommandController controller, SubCommandParseOption option)
   bei Microsoft.DocAsCode.SubCommands.CommandController.Create()
   bei Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
docfx 2.40.1.0
`

I tried copying the quoted parameters and removing the quotes and escapers from them. It worked afterwards, so it seems as if those parameters should not be escaped like that.

### Repro steps
Steps to reproduce:
1. Clone repo from https://github.com/DigitalFlow/FAKE-DocFx-Issue

2. Run build.cmd

3. Execution should fail with error as above

### Expected behavior
There should be no illegal path error.

### Actual behavior
An illegal characters in path error is being thrown.

### Known workarounds
None that I know of.

### Related information 

* Operating system: Windows 10
* Branch: Master
* .NET Runtime, CoreCLR or Mono Version:
`
C:\Git\FAKE-DocFx-Issue>dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.402
 Commit:    3599f217f4

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`
* Indications of severity
* Version of FAKE (4.X, 5.X): 5.3
* (if performance issue) Performance information, links to performance testing scripts

### PR DESCRIPTION
**Pull request by DigitalFlow**
### Description
This PR switches the DocFx module to use Args instead of the deprecated Process functions.

- fixes #2187 

Unfortunately neither building the project using `fake run` nor using `dotnet` builds successfully.
But this was also the case for me before I did the changes.
Some hints whether the stringify functions are ok as they are would be great.

## TODO
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)

### CODE REVIEW

**Comment by matthid** [comment]
> Unfortunately neither building the project using fake run nor using dotnet builds successfully.

Can you open an issue with the problem description? It is a bit unusual that this wouldn't work considering the amount of CI-Systems this stuff is running on.

**Comment by DigitalFlow** [comment]
> > Unfortunately neither building the project using fake run nor using dotnet builds successfully.
> 
> Can you open an issue with the problem description? It is a bit unusual that this wouldn't work considering the amount of CI-Systems this stuff is running on.

Yes, sure. For the FAKE build it seems that chocolatey was missing, we might want to add that to the build requirements.
I'll redirect the output to a file and open a case afterwards.

It would be awesome if you could check the file changes in the commit, I hope I used the Args module as it was intended.

**Comment by matthid** [comment]
@DigitalFlow My suggestion would be to go with arg-lists all the way and switch to the `CreateProcess` API (and add a test for this bugfix, a single one is enough).
This has the advantage that no string building is required at all.

**Comment by kblohm** [comment]
Thanks for taking care of this!
But there are some things that are not going to work properly right now:
You need something along the lines of `boolParam`, `optionParam` etc. Right now you generate arguments like `overwrite` as `--overwrite=false` or `--overwrite=true` instead of leaving the argument when it is false and just specifying `--overwrite` when it is true. Similairly for strings,  you generate `--ApiSourceFolder=""` when nothing is specified instead of leaving the argument off. Same goes for `Option`.
If you need any help, let me know.

@matthid as you deprecated the params-stuff (e.g. `boolParam`) from the `ProcessModule`, is there any alternative now or should every module do its own thing? I know the `ArgsModule` can be used for escaping, but there is no support for actually "specifying" the arguments similair to what the `ProcessModule` had before.

**Comment by DigitalFlow** [comment]
@matthid: Would be interested in what to use as replacement for the stringification which was done in boolParam, stringParam, ... as well.
Adding a unit test and using CreateProcess is fine.

**Comment by matthid** [comment]
> I know the ArgsModule can be used for escaping, but there is no support for actually "specifying" the arguments similair to what the ProcessModule had before.

Yes it would be nice to have the same helpers for list based parameter generation, I think @vbfox has written a library we might want to steal  ;)

**Comment by vbfox** [comment]
`s/steal/reference/` 😉

Joke aside you can copy paste it if you want it's MIT but I can cross license to Apache 2 if you need :) Just please steal the printf integration ( https://github.com/vbfox/FoxSharp/blob/master/src/BlackFox.CommandLine/Readme.md ) :

```fsharp
let cmd =
    CmdLine.empty
    |> CmdLine.append "build"
    |> CmdLine.appendIf noRestore "--no-restore"
    |> CmdLine.appendPrefixIfSome "--framework" framework
    |> CmdLine.appendPrefixf "--configuration" "%A" configuration
    |> CmdLine.appendf "-n=%s" name
    |> CmdLine.toString
```

Obviously I would prefer a reference as it will avoid fixing issues in two places (And I love that habit of JS ecosystem of making small dedicated libraries) but fake having some code so serialize / deserialize command lines already make it less simple than "just use it" ( https://github.com/vbfox/FoxSharp/issues/1 )

**Comment by matthid** [comment]
@vbfox Yes referencing is an option but I don't think people should need to convert types between several libraries in order to start a process. I think process starting should be in the fake core.

**Comment by vbfox** [comment]
Can't you reference it in Fake.Core.Process ? is there a technical limitation or just a wish to keep fake core dependency free ?

**Comment by matthid** [comment]
@vbfox No technical limitation, more that we should have a set of types working well together and the wish to have breaking changes around them in control ;)

**Comment by matthid** [comment]
Or to be clear: I'm not against it. I just *feel* like having it in the repository leads to fewer issues in the long run..

**Comment by DigitalFlow** [comment]
@matthid: So how to continue? Copy the code you linked to a separate class and use it?

**Comment by matthid** [comment]
@DigitalFlow sorry we got a bit sidetracked. What this pr needs is a basic test showing what this fixes

**Comment by matthid** [comment]
any interest in finishing this?

**Comment by DigitalFlow** [comment]
Yes, definetly.
As was shown by @kblohm, some parameters are not handled properly.
So I need to either rework the logic, or use the library of @vbfox.

**Comment by matthid** [comment]
Yes just skip all manual escaping and just build a list of string is probably the easiest option

**Comment by DigitalFlow** [comment]
Yes, we did no escaping, however building the strings had some issues, for example boolean options that were passed as - -option=true instead of just passing - -option.
I have the feeling that we should have a central module for such stringifications, such as in ProcessHelper.

**Pull request merged**
