### PR TITLE
FSharp.Compiler.Service 10.0.1

### PR DESCRIPTION
**Pull request by forki**
Trying to update FAKE to FSharp.Compiler.Service 10.0.1

### CODE REVIEW

**Comment by forki** [comment]
@matthid  @dsyme any ideas why the resolution breaks?

**Comment by matthid** [comment]
I think we make some assumptions in the caching code and FSharp.Compiler.Service broke at least some of them. For example the code seems to generate a differently named "entry" method (might be the wrong word) now:
https://travis-ci.org/fsharp/FAKE/builds/200609285#L2450 (I'm not sure why we only see this on travis...)

**Comment by forki** [comment]
I see same thing locally and I'm not sure what to do

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L288-L306 and https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L317 might need to be updated. I don't know where the corresponding code in FCS sits. 

Can you look at the generated dll file with reflector? Maybe they added an API for that so we don't need to manipulate strings anymore? /cc @dsyme

**Comment by matthid** [comment]
@forki  did you figure it out?

**Comment by forki** [comment]
nope

2017-02-20 15:47 GMT+01:00 Matthias Dittrich <notifications@github.com>:

**Pull request merged**
