### PR TITLE
Update FakeRuntime to use NetStandard 2.0.3

### PR DESCRIPTION
**Pull request by BlythMeister**
### Description

I keep running into https://github.com/dotnet/standard/issues/708 and this is apparently fixed in 2.0.3

I'm not sure if this has any other effects...

### CODE REVIEW

**Comment by matthid** [comment]
But we only use the package to have the reference assemblies, fake doesn't use the msbuild stuff, nor should it influence dependency resolution?

**Comment by matthid** [comment]
(note I'm fine with the update if stuff still works ;))

**Comment by BlythMeister** [comment]
Although the error was the same, the cause wasn't...I had corrupted my local nuget cache.

**Comment by BlythMeister** [comment]
This doesn't work and not sure we reallly need it...

**Comment by matthid** [comment]
why does it not work?

**Comment by matthid** [comment]
Maybe I'm just merging this in, there might be some other place where `2.0.2` is hardcoded but we probably should unify those if that is the case

**Comment by BlythMeister** [comment]
Err ok 😂

**Comment by matthid** [comment]
But yeah some wtf is going on with these builds :/

**Comment by matthid** [comment]
Fake reports

```
TemplateIntegrationTests        00:00:00.4552954   (DotNet CLI Template Integration tests failed.)
```

But output says:

```
[16:00:31 INF] EXPECTO! 8 tests run in 00:02:46.8871496 for Fake.Core.CommandLineParsing.Tests – 8 passed, 0 ignored, 0 failed, 0 errored. Success! <Expecto>
[16:00:31 INF] EXPECTO?! Summary...
Passed:  8
	Fake.Core.CommandLineParsing.Tests/issue #2025
	Fake.Core.CommandLineParsing.Tests/reference fake core targets
	Fake.Core.CommandLineParsing.Tests/use external paket.dependencies
	Fake.Core.CommandLineParsing.Tests/context exists
	Fake.Core.CommandLineParsing.Tests/reference fake runtime
	Fake.Core.CommandLineParsing.Tests/simple runtime error
	Fake.Core.CommandLineParsing.Tests/simple failed to compile
	Fake.Core.CommandLineParsing.Tests/no dependencies hello world
Ignored: 0
Failed:  0
Errored: 0 <Expecto>
```

**Comment by matthid** [comment]
Ok scratch that I know what's going on

**Comment by BlythMeister** [comment]
That makes one of us 😂

**Comment by matthid** [comment]
Yes it wanted the latest changes/fixes from release/next ;)

**Comment by BlythMeister** [comment]
@matthid this all good now?

**Comment by matthid** [comment]
looks like it is

**Pull request merged**
