### PR TITLE
General FAKE improvements

### PR DESCRIPTION
**Pull request by matthid**
See #1083. Bah I hope its the last time now. This turned out to be way harder than imagined.

### CODE REVIEW

**Comment by forki** [comment]
@bjartwolf can you please verify latest alpha works for you?

**Comment by bjartwolf** [comment]
Testing now. Letting you know in a minute...

**Comment by bjartwolf** [comment]
Works fine on TeamCity.

**Comment by forki** [comment]
thx. starting proper release

**Comment by matthid** [comment]
Lets hope the best, thanks @forki for all the patience and sorry for breaking things several times (at least we now have more unit tests).

**Comment by forki** [comment]
don't worry. I'm happy that you and other people care so much about the tool.

**Comment by forki** [comment]
image

I updated FAKE in Paket and get this when running build on https://github.com/fsprojects/Paket/commit/844dcb8e26749ce9fb332e62ef4322e92222f454

**Comment by forki** [comment]
says it cannot load a type in the assembly

**Comment by matthid** [comment]
looking into it...

**Comment by matthid** [comment]
Sadly I cannot reproduce, tried to checkout the git hash and 'paket restore -f'. Does "-pd" give the full error message?

**Comment by forki** [comment]
ok deleted .fake folder - seems to work now

**Comment by forki** [comment]
I guess we should invalidate all caches. Can you submit a PR which does that? maybe we need a cache version encoded in the file name.

**Comment by matthid** [comment]
hm, maybe something to do with included scripts, but I thought we handle them in the caching code.... Could you send me the broken assembly (out of the recycle bin)?

**Comment by matthid** [comment]
Do you mean FAKE version?

**Comment by forki** [comment]
In paket we have: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Nuget.fs#L25 

whenever we change that property paket will not take older caches

**Comment by matthid** [comment]
Ah you mean a cache version, got it. For this particular change I added a warning file so it should have invalidated already...

**Comment by matthid** [comment]
Therefore I assume something else is to blame here.

**Comment by matthid** [comment]
I think it's better to print the exception, invalidate the cache and recompile if loading the cached assembly fails, this should work without adding any version. And it works in the case that something did go wrong when writing the cache (power outrage for example). I can come up with a PR if you agree (actually I wanted to include that but I decided to feature stop after it broke again and again :D ).

**Comment by forki** [comment]
sounds good

**Comment by matthid** [comment]
By the way with this change we can finally move FAKE forwards in the sense that we can mark some ot the `<AutoOpen>` modules as obsolete if we want to (as people will finally see the warnings and have a opportunity to move away). Whats the status there, is this still on the wish list?

**Pull request merged**
