### PR TITLE
Add all assembly metadata to AssemblyVersionInformation type

### PR DESCRIPTION
**Pull request by amazingant**
PR for #822 as requested by @dsyme

Replaces the `Version` and `InformationalVersion` values being generated with the `AssemblyVersionInformation` type with a value for every assembly attribute.

As the new values are named after their attribute type names, this is a breaking change for anyone expecting `Version` instead of `AssemblyVersion` and `InformationalVersion` instead of `AssemblyInformationalVersion`.

Likewise, the newly-named `AssemblyVersion` and `AssemblyInformationalVersion` values are no longer generated by default, and must be included in the collection of provided attributes.

### CODE REVIEW

**Comment by forki** [comment]
thx

**Comment by Ravadre** [comment]
Hi,

@amazingant - this PR seems to have broken generating AssemblyInfoVersion when Metadata attribute is used.

Before this PR generated code looked like this:
```
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyMetadataAttribute("githash","cc5fd8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "LocalBuild";
        internal const string InformationalVersion = "LocalBuild";
    }
}
```

After the PR:
```
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyMetadataAttribute("githash","cc5fd8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyMetadata_githash = "githash","cc5fd8";
    }
}
```

Note, that string const has a value of `"key","value"` which is not valid code. Reason why this is the case seems to lie in L183:
`fun x -> sprintf "        internal const %s %s = %s;" x.StaticPropertyType x.StaticPropertyName x.StaticPropertyValue`

`x.StaticPropertyValue` seems to have value that goes into attribute data, when using most attributes where value is a single string, this is OK, because the property will have value like `"0.2"`, for Metadata though - it will contain 2 string values.

**Comment by amazingant** [comment]
@Ravadre Sorry, forgot to supply a different `StaticPropertyValue` for metadata attributes. Fixed with #1399

**Comment by Ravadre** [comment]
@amazingant Hi, that's great, thanks a lot!

**Pull request merged**
