### PR TITLE
Install Instruction

### PR DESCRIPTION
**Pull request by ShalokShalom**
### Description

Adds install instructions to the README, as they are not there yet.

### CODE REVIEW

**Comment by yazeedobaid** [comment]
@ShalokShalom Thanks for the contribution!
Could you please link this #2576 issue you opened to this PR and push it again to fix the build?

**Comment by ShalokShalom** [comment]
I dont know, how to push again 😁

You mean simply creating a new commit?

**Comment by yazeedobaid** [comment]
yes please

**Comment by ShalokShalom** [comment]
Uups, I accidently added two, since Github bugged

**Review by yazeedobaid — APPROVED** [review]
Thanks

**Pull request merged**
