### PR TITLE
Partial fix for #1395

### PR DESCRIPTION
**Pull request by BlythMeister**
Targets now fire as early as possible.

However, targets will not move onto the next level until all targets on that level are completed.

Therefore, in the situation described in #1395 although T2.1 and T3 run along side each other, T2.2 waits until the longer running T3 has completed before starting even though it has no dependency on it.

### CODE REVIEW

**Comment by BlythMeister** [comment]
Hey @forki (or any other maintainer), any chance of getting this reviewed/merged?

**Comment by forki** [comment]
This looks like it's changing a lot of the internals. That's very risky.

@matthid  what do you think?

**Comment by BlythMeister** [comment]
@forki @matthid I have added additional test coverage of scenarios and happy to add more if you can describe any :)

**Comment by matthid** [comment]
Might be a candidate to rebase on top of FAKE vnext (https://github.com/fsharp/FAKE/pull/1281)?

However, this probably means that is not released anytime soon... As I'm currently quite busy.

**Comment by matthid** [comment]
Otherwise it looks like a logical change to make... Do a lot of people depend on the parallel processing?

**Comment by BlythMeister** [comment]
As a compromise, I could look to make a flag which is passed on command like to run targets as early as possible? 
That way it's not a change unless you opt in for it (which I would then do on my build script)

**Comment by forki** [comment]
I don't think we need a flag. Just enough confidence that it's correct

Am 12.10.2016 19:45 schrieb "Chris Blyth" <notifications@github.com>:

**Comment by BlythMeister** [comment]
Ok, I've tried to create test scenarios to cover basics,  the key to the change is the level adjustments. 
I'm not sure what else I can do to increase confidence,  but if you have anything I can try and implement it.

**Comment by forki** [comment]
we will put that in alpha for next minor version

**Comment by BlythMeister** [comment]
@forki there has been a few minor releases since october..any idea when this can be merge?

**Pull request merged**
