### PR TITLE
Fix 1267

### PR DESCRIPTION
**Pull request by matthid**
Bugfix & Test fixes, see #1267

### CODE REVIEW

**Comment by matthid** [comment]
I have problems with the last test
```
tmp8A1C.tmp.fsx(2,1): error FS3031: The type provider 'C:\PROJ\FAKE\src\test\Test.FAKECore\bin\Debug\test\FSharp.Data.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'file:///C:\PROJ\FAKE\src\test\Test.FAKECore\bin\Debug\test\FSharp.Data.DesignTime.dll' or one of its dependencies. The system cannot find the file specified.
```

For a script like this:

```
#r "C:\\PROJ\\FAKE\\src\\test\\Test.FAKECore\\bin\\Debug\\test\\FakeLib.dll"
open Fake
traceFAKE "TEST_FAKE_OUTPUT"
```

Maybe related to FSharp.Compiler.Service upgrade to v3?

**Comment by matthid** [comment]
Hm 2.0.0.6 exhibits the same behavior. Did we introduce some `FSharp.Data` stuff to `FakeLib` lately?

**Comment by forki** [comment]
öhm no!?

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/commit/ee816cfd65fa6efc156f2696b306ee159140216c

**Comment by matthid** [comment]
Should be bundle `FSharp.Data.DesignTime.dll` now or what?

**Comment by forki** [comment]
no!?

2016-06-18 12:04 GMT+02:00 Matthias Dittrich <notifications@github.com>:

**Comment by matthid** [comment]
I think either reverting the `Add new GitVersionHelper` commit or bundling the dependency would fix the problem.

@forki did you already release this commit? Because I think this will break a lot of scripts. If it's already released I might be wrong though.

/cc @trondd

I THINK we actually need to bundle `FSharp.Data.DesignTime.dll` when we add a reference to `FSharp.Data` in `FakeLib`. This is because we are compiling scripts with a dependency to `FakeLib` and the compiler seems to eagerly require type-provider design type assemblies at compile time (even when they are referenced indirectly), no matter if the code we try to compile actually needs it. Is this a bug in the F# compiler or working as intended? @dsyme 

AppVeyor is now green again with reverting.

**Comment by matthid** [comment]
Everything is green again :)

**Comment by forki** [comment]
So what about the git version helper? Can we do it without fsharp.data?

**Comment by matthid** [comment]
Yeah why not? Maybe @trondd can send a reworked version using `Newtonsoft.Json` only for example. 

On the other hand we can still decide to bundle the `DesignTime` assembly, but lets get back to green fast :)

**Comment by trondd** [comment]
Whops! I thought I had solved that problem with the `DesignTime` assembly issue, but apparently not. Just rollback and I'll rewrite it with `Newtonsoft.Json` instead.

**Comment by matthid** [comment]
Yeah I don't have an idea why it's needed, maybe a F# compiler expert can explain if this is a bug?

**Comment by forki** [comment]
Awesome! Thanks soo much.

**Pull request merged**
