### PR TITLE
Release Candidate 17

### PR DESCRIPTION
**Pull request by matthid**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I think we should include #1958 before

Sorry, I didn't had the time to send a PR before.

**Comment by matthid** [comment]
@MangelMaxime Yes we can do stuff like this after the release as well. I feel like we have no critical issues or blockers open at the moment.

**Comment by MangelMaxime** [comment]
Ok then i agree with you. 😊

**Comment by BlythMeister** [comment]
Imo, we should have https://github.com/fsharp/FAKE/pull/1959 in before we release.

**Comment by matthid** [comment]
@BlythMeister We can still fix bugs after release - it's not the end of the world :)

**Comment by BlythMeister** [comment]
True story!

**Pull request merged**
