### PR TITLE
Retrieve the ProgramFilesX86 value by exclusively relying on System.Environment

### PR DESCRIPTION
**Pull request by bbenoist**
#### Related documentation
- https://msdn.microsoft.com/en-us/library/system.environment.specialfolder.aspx
- http://stackoverflow.com/a/4514110
#### :warning: Warning

As I am a newcomer on FAKE, please note that I did not tested the code more than that:
- I build it only on a 64-bit Windows using both `build.cmd` and `FAKE.sln`
- I only ran it to build my own (and private) source code.

IMHO, it might be careful to test this PR on every platform targeted by FAKE.

### CODE REVIEW

**Comment by forki** [comment]
did you encounter a bug or why do we need to change that?

**Comment by bbenoist** [comment]
Nope. In fact, I had recently encountered the same problematic and resolved it by using those 4 lines based only on .Net :sweat_smile:

As I find the solution to be more maintainable (moves the detection to the .Net framework) and concise than making guesses on environment variables, I just wanted to inform you about such an alternative...

**Comment by forki** [comment]
I'm in favor of using the .NET stuff, but I don't remember why we have that hack. Maybe it's breaking...

**Comment by bbenoist** [comment]
Here are some commits affecting this function (from oldest to latest):
1. caa473327fd000779cf9f0511f620378a1d44957 Try to replace [ProgramFiles] and [ProgramFilesX86] in config file.
2. fea8435ed639fe6849d7c39098182001a9efb837 Move ProgramFilesX86 into EnvironmentHelper.fs
3. b4e468e2048fc7c775ba3796ed6b55eebace1d56 Using Path.Combine if possible.
4. 0ef901d1ad11a06e57ca60d7ffd2f92413fd09de Fixed issue #49, Fake.Deploy failures.
5. 146945d8a1739772f68099c3740ddeed4ef90b68 Handle problems with ProgramFilesX86 on mono - https://github.com/tpetricek/FsLab/pull/32

IMO, modifications of `ProgramFilesX86` in 3 and 4 would have been unnecessary with an implementation relying on .Net. Only 5 seems to have interesting arguments against using the .Net way because it might throws exception on non-Windows platforms. However this can be managed with a proper try catch statement.

As I am not yet accustomed with Mono, there is something that I do not understand. What's the point of using `ProgramFilesX86` outside of a Windows environment? Should'n it be avoided by throwing errors in such contexts?

**Comment by bbenoist** [comment]
[Environment.cs - .NET Reference Source](http://referencesource.microsoft.com/#mscorlib/system/environment.cs) and [Environment.cs  - Mono](https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs) answered my questions but have different behaviors when the information is unavailable.
Microsoft's implementation throws an exception whereas Mono's returns an empty string.

:cry:

**Comment by bbenoist** [comment]
cc @spouliot

**Comment by matthid** [comment]
All this stuff has changed anyway in the netcore version. I'll close this fow now. Feel free to send again against the new code.

**Pull request closed without merging**
