### PR TITLE
traceStartTask / traceEndTask: use 'use' block

### PR DESCRIPTION
**Pull request by 0x53A**
So it seems in my previous PR (https://github.com/fsharp/FAKE/pull/1379) I missed a few cases ...

The whole try / finally stuff just adds noise (in my opinion), what do you think about this IDisposable approach?

If you like it, I will go through all files (a full text search for traceStartTask found 114 lines in 59 files, so totally manageable).

### CODE REVIEW

**Comment by 0x53A** [comment]
In many cases it explicitly either closes the task or throws, so maybe this was originally on purpose?

Another approach could be to walk the stack on close, and close everything until the specified tag.
(e.g. if I call open "A" -> open "B" -> close "A", then B is implicitly closed.)

Then I could revert my previous pr and it would "just work".

**Comment by forki** [comment]
I like the idea of the use thingy. Can you add that everywhere?

**Comment by 0x53A** [comment]
Ok that should be everything this time

**Comment by forki** [comment]
thanks so much

**Pull request merged**
