### PR TITLE
upgrade paket.core to support net5.0

### LINKED ISSUE #2564: invalid parameter 'net50' after >= or < in '== net50' while upgrading netcoreapp3.1 to net5.0
### Description

Error while targetting net5.0 framework.

### Repro steps

1. dotnet new -i Saturn.Template
2. md saturn2net5
3. dotnet new saturn -lang F#
4. Change TFM in saturn2net5.fsproj TargetFramework as: net5.0
5. Change TFM in paket.dependencies as: framework: net5.0
6. dotnet new tool-manifest --force
7. dotnet tool install paket
8. dotnet tool install fake-cli
9. dotnet tool install saturn.cli
10. dotnet paket update
11. dotnet fake build -t run

### Expected behavior

Build and run project successfully on net5.0

### Actual behavior

Producing error:
> There was a problem while setting up the environment:
> -> Error during parsing of 'D:\Work\iprnd\fs\ipstackNG21\saturn2net5\paket.lock'.
> -> invalid parameter 'net50' after >= or < in '== net50'
> Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.

### Known workarounds

Still searching...

### Related information 

* Operating system Windows 10
*  Version of .Net Core
> .NET SDK (reflecting any global.json):
>  Version:   5.0.101
>  Commit:    d05174dc5a
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19041
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

* Version of Paket (5.257.0)
* Version of FAKE-CLI (5.20.3)
* Version of SATURN.CLI (0.12.1)
* Version of F#
> D:\Work\iprnd\fs\ipstackNG21\saturn2net5>dotnet fsi
> Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0

### LINKED ISSUE #2565: Invalid parameter 'net5.0-windows10.0.17763.0'
### Description

When trying to build my solution with just `dotnet build`. It works. But using fake I get an error

### Repro steps

1. Clone [MiniScaffold](https://github.com/TheAngryByrd/MiniScaffold)
2. Add `nuget Informedica.Utils.Lib` and `Microsoft.Data.SqlClient` to dependencies 
3. Run `paket install` to install the dependencies
4. Run `dotnet fake build -t dotnetbuild`

See my below comments that demonstrate the problem in isolation.

### Exptected behavior

The solution builds, just like running `dotnet build`.

### Actual behavior

> There was a problem while setting up the environment:
> -> Error during parsing of 'D:\Development\Informedica\libs\Informedica.ThrowAwayDb.Lib\paket.lock'.
> -> failed to parse line '      Microsoft.CSharp (>= 4.5) - restriction: || (&& (< monoandroid9.0) (< net45) (< net5.0-windows10.0.17763.0) (>= netstandard1.3) (< xamarinmac)) (>= uap10.0) (>= xamarinios)' (invalid parameter 'net5.0-windows10.0.17763.0' after >= or < in '< net5.0-windows10.0.17763.0) (>= netstandard1.3) (< xamarinmac)) (>= uap10.0) (>= xamarinios)') (Could not parse 'framework: restriction: || (&& (< monoandroid9.0) (< net45) (< net5.0-windows10.0.17763.0) (>= netstandard1.3) (< xamarinmac)) (>= uap10.0) (>= xamarinios)' as key/value pairs.)
>         -  invalid parameter 'net5.0-windows10.0.17763.0' after >= or < in '< net5.0-windows10.0.17763.0) (>= netstandard1.3) (< xamarinmac)) (>= uap10.0) (>= xamarinios)'
>         -  Could not parse 'framework: restriction: || (&& (< monoandroid9.0) (< net45) (< net5.0-windows10.0.17763.0) (>= netstandard1.3) (< xamarinmac)) (>= uap10.0) (>= xamarinios)' as key/value pairs.
>         -> invalid delimiter at position 22
> 

### Known workarounds

Not using fake

### Related information 

fake version: 5.20.4-alpha.1642

.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

### PR DESCRIPTION
**Pull request by yazeedobaid**
### Description

This PR upgrades `Paket.Core` to the latest beta release `6.0.0-beta8` to support .NET 5 in dotnet core build of FAKE. The legacy project is still using `Paket.Core` version `5.257`

During the upgrade, the following has been done:
1. Removed the `Expecto.testAdapter` since it is archived by the maintainer ([repo link](https://github.com/adamchester/expecto-adapter)) and conflicts with `FSharp.Core` in which it needs `FSharp.Core` < 5.0.0
2. `FSharp.Core` has been pinned to `5.0.0` since `Packet.Core` has `FSharp.Core` pinned to `5.0.0`, please see the following [link](https://github.com/fsprojects/Paket/blob/f7b3986b5fc29ae1e79f895fb530877173dd9503/paket.dependencies#L6)

I have tested the changes on the two cases for the two issues mentioned below. The new build of `fake-cli` which uses `Paket.Core` latest beta build, will parse the lock files generated from Paket CLI tool successfully.

- fixes #2564
- fixes #2565

## TODO

Feel free to open the PR and ask for help

- [x] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists - Since it is an upgrade in the dependencies of FAKE, currently I cannot think of a way to add tests to this.
- [x] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [x] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [x] (if new module) the module is in the correct namespace
- [x] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [x] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by matthid** [comment]
> Since it is an upgrade in the dependencies of FAKE, currently I cannot think of a way to add tests to this.

Given this repository bootstraps itself in the release process. I'm usually not too worried. If I want to be 100% safe I release a prerelease and try to build and release with the prerelease (there were some occasions where I did this). But usually there is no easy way to get the test-suite green with something that is broken.

Btw if you ever need a private channel/chat/question, feel free to add me on twitter (@matthi__d) or send me a mail to the one on the github profile.

**Comment by yazeedobaid** [comment]
Thanks Matthias !
I Will try that. Do you have any clue why the `intellisense.fsx` and files that are auto-generated by FAKE in `.fake` directory got deleted after the run of the script. This is the issue that causes the build to fail after the upgrade in integration tests.

**Comment by matthid** [comment]
@yazeedobaid Nothing that pops to my mind, I can tell you that we use Paket.Core APIs to generate those scripts and those scripts are not actually used by FAKE for running the script - they are, as hinted by the name, only used for intellisense in IDE, and strictly speaking not even all IDEs as last time I remember VSCode/Ionide used FAKE APIs instead.
The idea was to (re-)create those fsx-files whenever you run a script, such that after the first run you can have intellisense for all FAKE packages you use.

**Comment by matthid** [comment]
I took a brief look, maybe there is some other underlaying issue, and the test ` Fake.Core.Globbing.Tools.Tests/Test try find tool folder in sub path` is failing with a different message. We also don't write the intellisense file on failure and assert that in all integrations tests. So maybe the runner just fails with a different issue and therefore doesn't write the intellisense files (as expected). I'd suggest running those tests standalone (those integration tests just run fake.exe on a particular scenario and check if that works as expected).

**Comment by matthid** [comment]
And btw for running standalone I usually just setup the debugger in visual studio to the working directory of the test and the arguments accordingly and run it from there (and git clean the test directory when you are finished)

**Comment by yazeedobaid** [comment]
@matthid Thanks for the tips really helped
The issue was the `System.Reactive` package was updated from v4 to v5. I minimized the diffs and it was the cause in which auto-generated files in `.fake` directory were deleted after the fake runner finishes running the script.
For globbing tests, I also reverted the changes for them. I updated them to use the new process utility APIs but they cause the tests to fail.
I will keep this PR focused on the upgrade of `Paket.Core`. For globbing tests, In my opinion, I think new integration tests for new APIs in process utility should be added not replacing existing tests for deprecated APIs,. Do you have any other suggestions for them?

**Comment by halcwb** [comment]
Why is this so necessary update not merged?? 
@yazeedobaid did some great work, and now it seems that it is stalled.

**Comment by kerams** [comment]
Should be worth updating to 6.0.0 proper now.

**Comment by CumpsD** [comment]
@dsyme can you reopen this and have a look at it? without it FAKE will probably die quietly if it won't work for `net6.0`

**Pull request closed without merging**
