### PR TITLE
Upgrade to xUnit2

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
oups. now we get type load exceptions from xunit. https://travis-ci.org/fsharp/FAKE/builds/55802815#L3391

/cc @bradwilson

**Comment by forki** [comment]
as per @bradwilson on twitter: https://github.com/xunit/xunit/issues/158

**Comment by sergey-tihon** [comment]
The same issue https://travis-ci.org/fsprojects/FsUnit/builds/72982567#L1897

**Comment by jhamm** [comment]
When #928 is merged, the Travis CI build failures can be fixed by setting the new NoAppDomain bool parameter on the XUnit2 target.

**Comment by matthid** [comment]
Wow the travis link is still working.
I guess we can finally close this with the latest 4.60.0 release :)

**Pull request closed without merging**
