### PR TITLE
Add support for contentFiles to Fake.DotNet.NuGet packaging

### LINKED ISSUE #2144: Fake.DotNet.NuGet needs to support ContentFiles section in nuspec
### Description

Currently the Fake.DotNet.NuGet module does not support interpolation of the ContentFiles section, which means delivery of content files will not work correctly for .NET Core.  This is documented here:

https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

### Expected behavior

Definition of the ContentFiles element should be possible via `NuGet.NuGetParams` to inject the desired `files` elements.

### Actual behavior

Not possible to define.

### Known workarounds

Currently I'm hardcoding the element in `nuspecs` which are duplicated for the different use-cases, which isn't going to work long-term.

### Related information 

* Windows / MacOS / Linux
* master
* .NET Runtime, CoreCLR or Mono Version
* Fake.DotNet.NuGet 5.8.5

### Comments

I'm just reporting this error with the intention of providing a pull request, but I have to prioritise the work against other things, which will likely mean a week or two before that's possible.  If anyone else picks this up, great, but I'm intending on contributing 👍

### PR DESCRIPTION
**Pull request by chappoo**
Fixes #2144

### CODE REVIEW

**Comment by chappoo** [comment]
@matthid As per contribution docs, I branched from my fork `origin` `master` branch and created this PR to base on `upstream` `master`.  Is that correct?  I've seen other branches in `upstream` that have been branched / base off `release/next`.

**Comment by matthid** [comment]
@chappoo Usually the diff between master and release/next is not too big and github allows to change the target branch (and I already did) so not an issue. But where are the docs because currently targeting `release/next` is preferred...

**Comment by chappoo** [comment]
@matthid I was looking here: http://fake.build/contributing.html#Programming

**Comment by matthid** [comment]
@chappoo Thanks will try to update. Can you rebase or push an empty commit to re-trigger the CI processes (seems to have problems with changed branch target, maybe I was too fast)

**Comment by chappoo** [comment]
Done - rebased on `release/next`

**Comment by matthid** [comment]
No idea why this pr doesn't trigger any CI (we have many so I'd assume github is to blame)... Maybe close and add a new one?

**Comment by matthid** [comment]
Ok it looks like they have some problems: https://status.github.com/messages

**Comment by chappoo** [comment]
I saw the data consistency outage earlier - I think they had stopped all web-hooks as a precaution

**Comment by chappoo** [comment]
I might start again once they've fully resumed, will kill the PR / branch and start again, not sure I can open a new PR against a branch with a closed PR?

**Comment by matthid** [comment]
@chappoo Yes I think that's not a problem, you can push to the same branch after a previous PR has been merged and start a new PR (in fact that's what I'm doing all the time with the `release/next` branch on master)

**Comment by chappoo** [comment]
Looks like CI has magically started now

**Comment by matthid** [comment]
I think a small unit test for the new parameter  would make sense

**Comment by chappoo** [comment]
> I think a small unit test for the new parameter would make sense

I totally agree, I'm not familiar with the test setup here though.  Are there already unit tests for the NuGet module?

**Comment by matthid** [comment]
We recently added a more testable API (`CreateProcess`) and started to switch to it when new features are added (see https://github.com/fsharp/FAKE/pull/2120/files for example). The switch should be quite straight-forward and the latest documentation only actually lists the new API.

Once the module uses `CreateProcess` you would refactor an internal api which returns the `CreateProcess<T>` instance and use that for testing (see the other PR for details).

Let me know if that helps.

**Comment by matthid** [comment]
any interest in finishing this?

**Comment by chappoo** [comment]
@matthid The notification for this merge reminded me of this (old!) PR... appreciate the acceptance.

**Pull request merged**
