### PR TITLE
Node reuse on build servers causes trouble for subsequent builds

### PR DESCRIPTION
**Pull request by trondd**

### CODE REVIEW

**Comment by forki** [comment]
So this would enable it on TC right?

**Comment by trondd** [comment]
Bah, of cause the last minute change would fuck it all up. New patch in the air

**Comment by trondd** [comment]
If you want to be conservative I just change it to `(buildServer = TeamCity || buildServer = TeamFoundation)`

**Comment by forki** [comment]
Yes please

**Comment by forki** [comment]
ok NodeReuse = isLocalBuild would exclude TC. That would be ok

Is that what you meant?

**Comment by trondd** [comment]
Yes, but as I said, if you want to be on the safe side I can just limit it to TFS and TC. We're currently only using those two build server, but I would Guess others have the same trouble.

**Comment by forki** [comment]
probably better yes.

**Comment by trondd** [comment]
I created a new pull request with just the single correct commit to avoid cluttering the history, so just drop this one.

**Pull request closed without merging**
