### PR TITLE
Wix Helper Improvements

### PR DESCRIPTION
**Pull request by DigitalFlow**
Added tests for WiX Helper methods, fixed a bug and replaced some enum style properties to F# enums with XML commentary for easing usage.

### CODE REVIEW

**Comment by forki** [comment]
wow. cool stuff

**Comment by DigitalFlow** [comment]
You're welcome, I'm happy to contribute.
Shall I rebase before you merge?

**Comment by forki** [comment]
you send PR to develop branch.
Please try master the next time

**Comment by DigitalFlow** [comment]
Alright, thanks.

**Pull request merged**
