### PR TITLE
Use SPDX license expressions in the nuspec files and upgrade the .NET Core SDK version

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Comment by matthid** [comment]
Thanks for trying to take care of this. I tried it in the past but the stuff was in preview and I have given up after some time. The issue is (still):

```
Creating DEB package 'C:\projects\fake-6w516\src\app\fake-cli\bin\Release\netcoreapp2.1\linux-x64\fake-cli.5.17.0.linux-x64.deb' from folder 'bin\Release\netcoreapp2.1\linux-x64\publish\'
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018: The "DebTask" task failed unexpectedly. [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018: System.TypeInitializationException: The type initializer for 'Packaging.Targets.IO.NativeMethods' threw an exception. ---> System.IO.FileLoadException: Could not load liblzma. On Linux, make sure you've installed liblzma-dev or an equivalent package. [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    at Packaging.Targets.IO.NativeMethods..cctor() [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    --- End of inner exception stack trace --- [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    at Packaging.Targets.IO.XZOutputStream..ctor(Stream s, Int32 threads, UInt32 preset, Boolean leaveOpen) [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    at Packaging.Targets.DebTask.Execute() [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
C:\Users\appveyor\.nuget\packages\packaging.targets\0.1.84\build\Packaging.Targets.targets(98,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\projects\fake-6w516\src\app\fake-cli\fake-cli.fsproj]
```

I have reported this issue here: https://github.com/qmfrederik/dotnet-packaging/issues/84
The "fix" seems to be to use a global/local repro dotnet cli tool

**Comment by matthid** [comment]
Any interest in finishing this?

**Comment by teo-tsirpanis** [comment]
@matthid, I think I fixed it, but AppVeyor cannot install the FAKE CLI tools from Chocolatey.

**Comment by matthid** [comment]
I restarted the build and got (https://ci.appveyor.com/project/matthid/fake-6w516):
```
dotnet tool install -g dotnet-deb
A compatible installed .NET Core SDK for global.json version [2.1.801] from [C:\projects\fake-6w516\global.json] was not found
Install the [2.1.801] .NET Core SDK or update [C:\projects\fake-6w516\global.json] with an installed .NET Core SDK:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.603 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.206 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
```

So this version is not in AppVeyor as you mentioned in the first commit message?
I think I'll try fiddling around a bit with this.

**Comment by teo-tsirpanis** [comment]
> So this version is not in AppVeyor as you mentioned in the first commit message?

It should have been.

AppVeyor's documentation says that .NET Core SDK 2.1.801 is bundled

**Comment by matthid** [comment]
> It should have been.

Welcome to my world ;)

> Or do you prefer to immediately upgrade the tooling to 3.1? I would recommend that, because it is the next LTS release.

Yes I'm actually fiddling around with that as it allows to use local tools instead of installing dotnet-deb globally.

**Comment by matthid** [comment]
In any case, thanks! I never wanted to move forward because I thought this would be more work to get it to work but it seems to work with using the local-tool. Only thing missing was adding the packagereference to `Packaging.Targets` (at least that's what I hope)

Let's see if we break anyone ...

**Pull request merged**
