### PR TITLE
Added SonarQube support

### PR DESCRIPTION
**Pull request by Slesa**
and Centigrade as user

### CODE REVIEW

**Comment by forki** [comment]
awesome thx

**Comment by philipooo** [comment]
Maybe you could also add the optional /d:sonar.branch parameter.
In my case thats useful because analysis of feature branches will be seperated from the masters analysis if I populate it with e.g. git`s branch name.

**Comment by Slesa** [comment]
Should this possibly be a list of parameters to add with the /d switch or a simple string?

**Comment by philipooo** [comment]
A list of parameters to add with the /d switch would be also very nice and would bring lots of flexibility.

**Comment by Slesa** [comment]
Maybe you could test https://github.com/fsharp/FAKE/pull/1172, please?

**Pull request merged**
