### PR TITLE
The website libraries are now served via HTTPS.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Chrome complains about insecure scripts.

### CODE REVIEW

**Comment by matthid** [comment]
Thanks. I'm actually in the process of completely re-doing the website :). Will take care of this as well.

**Comment by matthid** [comment]
@teo-tsirpanis do you have those warnings on https://fake.build ?

**Comment by teo-tsirpanis** [comment]
> @teo-tsirpanis do you have those warnings on https://fake.build ?

No. But... this site... It's amazing! 😍 You could also set the page title to something more meaningful than `index`.

I think that the issue is fixed.

**Comment by matthid** [comment]
Oh yeah the title is only broken for the index, nice catch :/

**Pull request closed without merging**
