### PR TITLE
[Ready] Provide full fidelity of build options in Xamarin helpers

### PR DESCRIPTION
**Pull request by kentcb**
This PR adds full fidelity of build options to the Xamarin helpers. In other words, any relevant options available in `MSBuildParams` are now available in both `iOSBuildParams` and `AndroidBuildParams`. As an example of why this is useful, I am trying to use binary loggers for all my build pipelines, including Android and iOS builds. This will allow me to do so.

- [x] Tidy up warning messages
- [x] Test a full build on both Android and iOS
- [x] Port to netcore per [guidance](http://fake.build/contributing.html#Porting-a-module-to-FAKE-5)

### CODE REVIEW

**Comment by matthid** [comment]
To be usable in the new FAKE 5 the module needs to be ported to netcore. We have documentation around this [here](http://fake.build/contributing.html#Porting-a-module-to-FAKE-5). Let me know if you need help there.

**Comment by kentcb** [comment]
@matthid yeah, I'm struggling with the netcore migration a bit. I don't really know F#, so it's likely something simple. If you could take a look, that would be :100:

Basically, I followed the guidance as best I could, but there are two things I couldn't complete:

1. Running `build.cmd` on my machine just fails - something to do with GitHub. So I can't really validate that side of things works.
2. I wasn't sure how to obsolete the old module. Sounds silly, but by following the instructions the old module is no longer actually part of the source tree, so I don't really understand how this part works.

**Comment by matthid** [comment]
I think the only thing missing is to add the new module to the netcore solution file and to make it compile. Otherwise it looks good.

Marking as Obsolete just means adding `[<System.Obsolete("Where is the new module/User guideance")>]` to all members/functions/types of the old file (as we now have the code basically duplicated)

**Comment by kentcb** [comment]
@matthid making some progress on this, but confused why the netcore project files are multitargeting both NS1.6 _and_ NS2.0. Shouldn't it just be one or the other?

1.6 is causing me headaches because the existing code uses `XmlTextWriter`, which is part of 2.0 but not 1.6.

**Comment by matthid** [comment]
Yes having only netstandard20 is fine. We have netstandard16 because once we had that we didn't throw it away and another goal of FAKE 5 is to make the modules available in regular code more easily (so it makes sense for modules to support more frameworks than fake5 needs).

Also feel free to extend the contribution guide with that fact as others might come across similar situations as well.

**Comment by kentcb** [comment]
> so it makes sense for modules to support more frameworks than fake5 needs

Agreed, targeting lowest netstandard possible makes sense, but targeting multiple does not. By virtue of building for 1.6, the library can be consumed on a 2.0 platform.

Anyway, I've removed 1.6 from the Xamarin project. Hoping this build currently in progress is a winner.

**Comment by matthid** [comment]
In theory you are correct in practice having 20 in addition can lower the number or required dependencies for the consuming project...

**Comment by kentcb** [comment]
@matthid er, hmm, travis build failed but doesn't appear related to my changes....?

**Comment by kentcb** [comment]
I tried to force a rebuild, but it has failed just the same. Maybe it is something I've done....?

**Comment by matthid** [comment]
I have seen similar errors when the fake-netcore.sln file is invalid. Did you edit via 'dotnet sln fake-netcore.sln add newproj.fsproj' or by hand?

**Comment by kentcb** [comment]
I did it with VS. I'll review the file changes ASAP.

**Comment by kentcb** [comment]
:boom: Hopefully all good now, @matthid

**Pull request merged**
