### PR TITLE
Simplify buildPaths function

### PR DESCRIPTION
**Pull request by gusty**
### Description

 - Avoid unnecessary conversion to `seq`
 - Unify use of `collect`
 - Remove unused variables, unneeded parens

### CODE REVIEW

**Comment by matthid** [comment]
Hey thanks, good changes. Just to ensure we don't break anything. Do we have tests for this area? If not, can we add some around this code?

**Comment by gusty** [comment]
This project in general doesn't seem to have many tests.
Correct me if I'm wrong but all I see is 8 integrations tests and 0 unit tests.

**Comment by BlythMeister** [comment]
There is quite a bit more than that.  Look in src/test
Whilst there isn't great coverage, we are trying to add tests for changes to boost the set.

**Comment by matthid** [comment]
Yes indeed there are more and more unit tests (also "we have always done it like that" is not a good argument).

The advantage for me is that I need less time verifying or manually tesing the stuff, therefore - after the latest improvement in the core to simplify writing tests - I'm trying to focus more on tests as well (personally and for PRs)

Also I'm not sure but I believe there are already tests around globbing so if you find some tests already covering the code path that's fine and no new tests are required

**Comment by gusty** [comment]
Yes, there are tests for globbing https://github.com/fsharp/FAKE/blob/release/next/src/test/Fake.Core.UnitTests/Fake.IO.Globbing.fs but not sure if they cover the code path. I'll have to dig into it.

**Comment by gusty** [comment]
Actually I think it covers it, since buildPath it's used in `search` which is used in the `IEnumerable<'t>` interface for `LazyGlobbingPattern` which I see in the tests file.

**Comment by matthid** [comment]
Thanks, sorry but I'm just trying to reduce the number of manual fixups I have to do afterwards. Maybe I should also be more strict in reverting stuff if it fails after release.

**Pull request merged**
