### PR TITLE
Restore VS2015 support to open FAKE.sln

### PR DESCRIPTION
**Pull request by dedale**
Because we may not want to use VS2017 yet...

### CODE REVIEW

**Comment by matthid** [comment]
Oh nice, thanks

**Comment by dedale** [comment]
CI fails (even without my change) with 

> Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.

(Well I see other error message, but I guess this is the problem).
Will try to repro on my machine, but I'm a newbie in the magic world of .NET core...

**Comment by matthid** [comment]
Yes your change looked fine. Will take a look soon when. I merge and test the open PRs. Sorry maybe the new sdk release broke something here as well...

**Comment by dedale** [comment]
Thx, no hurry

**Comment by matthid** [comment]
Hm, seems like github couldn't handle what I was doing. Basically, I removed your revert commit and merged the PR. But it was too much for github, sorry

**Comment by dedale** [comment]
No problem, thx

**Pull request closed without merging**
