### PR TITLE
added executeFSIWithArgsAndReturnMessages

### PR DESCRIPTION
**Pull request by pr-yemibedu**
Added executeFSIWithArgsAndReturnMessages to coincide with existing executeFSIWithArgs and executeFSIWithScriptArgsAndReturnMessages functions. This brings inline functionality to give the caller a handle on messages generated on execution.

### CODE REVIEW

**Comment by matthid** [comment]
I can take it but I think this module needs a complete redesign/new api.

**Comment by pr-yemibedu** [comment]
Hello,
 Since I still use FAKE 4.63.2 for my projects, this would help greatly. If you also want a general rewrite, that can happen as well. Should that be discussed on *gitter.im* or should there be a ticket with the pending issues of the module? Thank you. Good day.

**Comment by matthid** [comment]
If we merge this into master it will not land in any 4.X release anyway.

**Comment by pr-yemibedu** [comment]
Hello,
 I did not know that some merges were being excluded. Is it the case that fixing or cleaning for the 4.x is not fruitful for the efforts? I wanted to have this available from upstream. You let me know what the best course of action should be. Thank you. Good day.

**Comment by matthid** [comment]
One problem is that I never managed to get the Fake4 release process running on my system. So we always need to ask @forki nicely about a release.
The second problem is that we need this pr to go onto the hotfix_fake4 branch.

Strictly speaking this is not a hotfix, but since this is a FAKE 4 only feature anyway, I would not mind this change.

**Comment by pr-yemibedu** [comment]
Hello,
 I see this now under [General Considerations](https://fake.build/contributing.html#General-considerations). I will try to stay on track in the future. Thank you. Good day.

**Comment by matthid** [comment]
I'll merge this into master now. If you want to use is you can just use the next release of the 5.X package.

**Pull request merged**
