### PR TITLE
WIP: Implement file system change watching.

### PR DESCRIPTION
**Pull request by voiceofwisdom**
Created a wrapper around `FileSystemWatcher` that makes it easy to watch the disk for changes. Uses a glob pattern to filter the changes to a subset of the files. I had to reimplement globbing using a regex, the current implementation requires walking the file system every time, the regex can do a simple compare to see if a path is matched.

Example :
```f#
Target "Watch" (fun _ ->
    let stop = !! "c:/projects/watchDir/*.txt" |> WatchChanges (fun changes -> 
        RunTarget "Tests"
    )

    System.Console.ReadLine() |> ignore

    stop() //if you need to cleanup the watches.
)
```

There are two reasons I marked this as WIP. 

First, is I dont know if the documentation I added is sufficient. This seems to be cool enough to justify its own article in the docs, but I wanted to check before writing that.

Second, if you dont do something to keep FAKE from exiting, it will exit immediately after setting up the watcher. Hence the `ReadLine` at the end of the function. Personally I dont find this to be pleasant. To make this not required we would have to keep track of all running `WatchChanges` and prevent FAKE from exiting while they are running. What are others thoughts on this?

### CODE REVIEW

**Comment by forki** [comment]
hey cool. I will take a deeper look soon.

regarding the globbing change: cc @colinbull

**Comment by forki** [comment]
regarding your sample. Maybe WatchChanges could return IDisposable!? Then we could do:

     use stop = !! "c:/projects/watchDir/*.txt" |> WatchChanges (fun changes -> 
            RunTarget "Tests"
    )

   ...
   stop.Dispose() // or rely on default dispose

**Comment by colinbull** [comment]
This all looks good. Doesn't actually change the globbing implementation used in (!!) etc. It is in addition to I believe, unless I have missed something on my quick check. If this is the case happy to see this merged, as I have a potential use for it :+1:

**Comment by forki** [comment]
What happens if I add a new file which would match the pattern?

**Comment by colinbull** [comment]
Looks as if the even will simply get raised. If you want it in your file
set you would have to run (!!) pattern again. I think.

**Comment by forki** [comment]
my main use case at the moment is documentation / website creation. When i add a new *.md file I want to rerun the FSharp.Formatting.

**Comment by colinbull** [comment]
In that case, it is just a call to `Literate.ProcessDirectory` on the event? Isn't it, that will then consume the new file.

**Comment by forki** [comment]
no the same thing is needed to copy the new pictures and stuff like that.

**Comment by voiceofwisdom** [comment]
If you add a new file the standard `!!` glob will pick it up again when rerun. `WatchChanges` will raise a change event for new files that match the glob.

@colinbull  you are correct, this is another implementation of the glob. It should match the existing glob syntax exactly.

**Comment by forki** [comment]
@agross what do you think?

**Comment by agross** [comment]
This looks like a nice addition to FAKE. I'd say docs and tests are the main use cases.

**Comment by forki** [comment]
I remember you creating a similar issue, but can't find it

**Comment by forki** [comment]
thanks a lot.

**Comment by forki** [comment]
I changed it to IDisposable and merged it in order to try it out downstream.
I hope you can a bit of of docs in a new PR

**Comment by voiceofwisdom** [comment]
Created a pr for a small tutorial, #774.

**Pull request merged**
