### PR TITLE
replace fake header with FST-1027 - Beta 013

### PR DESCRIPTION
**Pull request by matthid**
See https://github.com/fsharp/FAKE/issues/1768

I decided to support `#r "paket:". As we use the FCS-Tokenizer multi-line strings and similar things work.
In fact 
```fsharp
#r "paket:
storage: none
source https://nuget.org/api/v2
source ../../../nuget/dotnetcore
 
nuget Fake.Core.Target prerelease
nuget FSharp.Core prerelease"
```

Looks quite nice.

As this currently prints 

```
E:\Projects\faketest\myscript.fsx (1,0)-(6,31): Warning FS0213: 'paket:
storage: none
source https://api.nuget.org/v3/index.json

nuget Fake.Core.Target prerelease
nuget Fake.Net.Http prerelease' is not a valid assembly name
```

The natural way to do it is:

```
#if FAKE_DEPENDENCIES
#r "paket:
storage: none
source https://nuget.org/api/v2
source ../../../nuget/dotnetcore
 
nuget Fake.Core.Target prerelease
nuget FSharp.Core prerelease"
#endif
```

Another way would be to disable warning `FS0213` (at least for strings starting with `paket: `)

### CODE REVIEW

**Comment by matthid** [comment]
Even better: As this thing is a warning only we can ignore that.

Maybe I can get @Krzysztof-Cieslak or @enricosada to remove this warning from Ionide as well (or even better provide intellisense within the `paket: ` string...)

Now 

```fsharp
#r "paket:
storage: none
source https://nuget.org/api/v2
source ../../../nuget/dotnetcore
 
nuget Fake.Core.Target prerelease
nuget FSharp.Core prerelease"
```

works without warning. Now I'll try to get the defaults right, such that `storage:none and the NuGet default source is not required (only when no other source is given)

**Comment by Krzysztof-Cieslak** [comment]
Both disabling warning in this particular case, and providing intellisense inside those strings should be doable and not too complex.

**Comment by matthid** [comment]
Now we get

```fsharp
#r "paket:
nuget Fake.Core.Target prerelease
nuget FSharp.Core prerelease"
```

Because we default to `storage:none` and the default NuGet `source`.

**Comment by matthid** [comment]
Ok if any string is given in `#r "paket: <data>"` and `<data>` is by accident a valid filename. The compiler will emit `FS0078` :
```
C:\projects\fake-6w516\integrationtests\core-use-external-paket-dependencies\temp\use_external_dependencies.fsx (1,0)-(1,25): Error FS0078: Unable to find the file 'paket: groupref Main' in any of
```
I hope  the workaround is to use `#r "paket: <data> //` and paket allows in-line comments.

**Pull request merged**
