### PR TITLE
update to FCS 35 across all projects

### PR DESCRIPTION
**Pull request by baronfel**
### Description

This updates FAKE's dependency on FCS to version 35, the latest major version. This is primarily done to allow the FAKE integration in FSAC to be updated along with the other dependencies FSAC bundles (see https://github.com/fsharp/FsAutoComplete/pull/590 for progress there).

This version introduces a few breaking namespace/module changes, which is the reason for the major version change, along with a few API surface area additions.  None of which are directly used by FAKE, but nonetheless FAKE must be updated in order to interop inside of FSAC nicely.

### CODE REVIEW

**Comment by matthid** [comment]
Thanks again, sadly that was conflicting with https://github.com/fsharp/FAKE/pull/2493.
Can you fix the conflict and I'll try to go ahaid and release an alpha

**Comment by baronfel** [comment]
Done! Let's see if CI is green here as well.

**Comment by matthid** [comment]
It did, thanks!

**Comment by matthid** [comment]
@baronfel you can try with `5.20.0-alpha.1566`

**Pull request merged**
