### PR TITLE
MSBuildHelper: Add BuildWebsite(s)Config.

### PR DESCRIPTION
**Pull request by ianbattersby**
Adds the ability to build websites with a configuration other than `Debug`.

Sorry it took so long to pull-request this @forki after our chat many months ago, completely slipped my mind!

### CODE REVIEW

**Comment by forki** [comment]
Is this breaking?

**Comment by ianbattersby** [comment]
Nope, should be backwards compatible, on purpose 👍

**Comment by ianbattersby** [comment]
PS. I did change a parameter name on an existing method to be consistent, but given F# as I know it (and the signature otherwise being the same) I thought this was safe.

**Comment by forki** [comment]
Good. Thanks. Will merge / release in Monday. If I get my Internet
connection back.

**Comment by forki** [comment]
Yes changing name is fine in fake. Changing types not so much...

**Comment by forki** [comment]
cool. thanks!

**Pull request merged**
