### PR TITLE
Release 5.2

### PR DESCRIPTION
**Pull request by matthid**

### CODE REVIEW

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/pull/1963
https://github.com/fsharp/FAKE/pull/1863

**Comment by matthid** [comment]
I think the appveyor failure has to do with https://github.com/ctaggart/SourceLink/issues/355 but it's a bit frustrating that an external package (`Octokit` depends on `SourceLink.Create.GitHub`) added this.

**Comment by baronfel** [comment]
eww, packaging failure: 
image

They expose sourcelink.create.github as an explicit dependency :(

**Comment by matthid** [comment]
@BlythMeister told me on gitter that there is a problem with this:

If we update our packages to FSCore 4.5 old runners will choke after updating (because of https://github.com/fsharp/FAKE/issues/2001).

Therefore the logical thing would be to leave the packages on the current FSharp.Core and only update the runner. But this is a bit hard to do with Paket (@forki for awareness) :(. Let's see...

**Comment by BlythMeister** [comment]
The fsharp.core issue could be fixed with a binding redirect?

**Comment by matthid** [comment]
sadly it's not so simple...

**Comment by BlythMeister** [comment]
😪 of course it's not...

**Pull request merged**
