### PR TITLE
feat: add basic support for GitHub Actions

### PR DESCRIPTION
**Pull request by Bomret**
### Description

Add basic integration with GitHub Actions.

## TODO

Feel free to open the PR and ask for help

- [x] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
    - just static helpers, no logic
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [x] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [x] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [x] (if new module) the module is in the correct namespace
- [x] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [x] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by Bomret** [comment]
@matthid I created a new PR from a fresh fork of the release/next branch

**Comment by matthid** [comment]
Do we need an 'installer' (see https://fake.build/buildserver.html) and a custom output configuration? For example to support custom tracing or coloring?

Even if the "default" works we should "pin" it in case we decide to change the defaults.

**Comment by Bomret** [comment]
I haven’t looked much at those features. I just wanted to add basic support, so one can check if the build is happening on GitHub and to access the provided env vars. Are the installer and output colorizing features a must have for basic support?

**Comment by Bomret** [comment]
@matthid I added the installer.

**Comment by matthid** [comment]
> Are the installer and output colorizing features a must have for basic support or could we iterate on this feature later?

Yes, we can always iterate but from an API perspective, it makes sense to have those APIs for consistency reasons (even if they do nothing). Thanks a lot!

**Pull request merged**
