### PR TITLE
Add BasePath support for NuGet pack

### LINKED ISSUE #1208: Allow the BasePath command option to be set when using the NuGetHelper
### Description

When using the NuGetHelper, it is currently not possible to specify the BasePath command option that the Nuget Pack command accepts.  Having this would enable the FAKE script to set the base path of the files defined in the nuspec file.
### Known workarounds

Use Shell.Exec to run NuGet pack with the needed BasePath parameter
### Related information
- https://docs.nuget.org/consume/command-line-reference#pack-command-options

### PR DESCRIPTION
**Pull request by TeaDrivenDev**
fixes #1208

### CODE REVIEW

**Comment by forki** [comment]
Can you please rebase? Thx

**Comment by matthid** [comment]
Please wait until I have fixed the master (which failed partly because of the broken paket release)

**Comment by matthid** [comment]
Ok master is "green" for the moment (there still is a transient error from time to time)

**Comment by TeaDrivenDev** [comment]
Done.

**Pull request merged**
