### PR TITLE
Add ability to create a release with a name different to version

### PR DESCRIPTION
**Pull request by BlythMeister**

### CODE REVIEW

**Comment by matthid** [comment]
Please use `Fake.Api.GitHub` instead?

**Comment by BlythMeister** [comment]
On this project I'm using fake 4 (and don't have capacity to update to 5 yet)

**Comment by matthid** [comment]
Yes next suggestion would have been to just copy the file to unlock yourself

**Comment by BlythMeister** [comment]
@matthid https://github.com/BlythMeister/Gallifrey/commit/7a0f9a7c0a2faf5a36c222ee8b1f598bb7906c23 :)

**Pull request closed without merging**
