### PR TITLE
Revert console encoding

### LINKED ISSUE #1461: Revert System.Console.OutputEncoding to not break the shell
### Description

When using any external tool from a FAKE script (MSBuild, test runners, Paket, …), after FAKE exits, the terminal is broken. I tried different console emulators (Windows console, PowerShell, ConsoleZ) and different shells (`cmd.exe`, PowerShell, bash), and all show the same behavior.

### Repro steps

1. Open a `cmd.exe` window.

1. Run FAKE with a target which invokes an external tool.

As I found out, [the assignment][assignment] of the output encoding before starting the process is the problem. The assigned value remains set after FAKE exits, which apparently breaks the input handling of the shell.

  [assignment]: https://github.com/fsharp/FAKE/blob/805ca9420e0234fe2ac8fe2033f28faeec2ebb40/src/app/FakeLib/ProcessHelper.fs#L27

### Actual behavior

After FAKE exits, I can't use the German Umlaut-characters. When I try to type an "Ä" for example, it doesn't appear on the screen, but now I'm able to delete already printed output from the console.

I reproduced this with `fsi`:

Screencast

### Known workarounds

Use FAKE in its own terminal window.

### Related information 

* Operating system: Windows 7
* .NET Runtime, CoreCLR or Mono Version: .NET 4.6.2

### PR DESCRIPTION
**Pull request by inosik**
Trying to fix #1461.

I tested it on my machine and it seems to fix the issue.

### CODE REVIEW

**Comment by matthid** [comment]
Do we need the same for FAKE 5? (src/app/Fake.netcore)

**Comment by inosik** [comment]
Yes, I think so.

But Fake.netcore doesn't reference FakeLib, so we need to do that somewhere else. Or we could change the whole thing to always save the encoding at program start and restore it when we exit.

**Comment by inosik** [comment]
Alternative implementation at #1580. We can close one of these after we decide which approach we take.

**Comment by matthid** [comment]
Used https://github.com/fsharp/FAKE/pull/1580

**Comment by matthid** [comment]
Thanks for taking care of this.

**Pull request closed without merging**
