### PR TITLE
Fix260chars win

### PR DESCRIPTION
**Pull request by davidpodhola**
When building a complex project on Windows (e.g. including deep structures like "C:\Users\DAVID~1.POD\Source\WORKSP~1\FSHARP~1\src\FSHARP~2\NODE_M~1\GR2FD0~1\NODE_M~1\maxmin\NODE_M~1\PRETTY~1\NODE_M~1\meow\NODE_M~1\INDENT~1\NODE_M~1\REPEAT~1\NODE_M~1\IS-FIN~1\node_modules\number-is-nan" ) the PathTooLongException is thrown.
I think there is nothing to do, but the build should go on.

(Sorry for the commit-revert-commit, I forgot to create the branch first)

### CODE REVIEW

**Comment by cdrnet** [comment]
Skipping files without any kind of hint or warning sounds a bit dangerous to me.

**Comment by davidpodhola** [comment]
@cdrnet you are right. What about the same warning `dir` produces?
dir 160 chars problem

**Comment by davidpodhola** [comment]
@cdrnet looks better?

**Comment by cdrnet** [comment]
Yes, much better - thanks!

**Pull request merged**
