### PR TITLE
paket update for fake runner FSharp.Core 4.7

### PR DESCRIPTION
**Pull request by drssoccer55**
Response to error message saying FAKE runner uses FSharp.Core 4.6 instead of latest FSharp.Core. I've worked around it locally but think the runner should be updated.

Following instructions from [issue 2001](https://github.com/fsharp/FAKE/issues/2001)

Forked, cloned, paket update, and submitted PR.

### CODE REVIEW

**Comment by drssoccer55** [comment]
image

Whoops forgot this update broke me too. Will have to update FAKE to get rid of the namespace.

**Comment by drssoccer55** [comment]
Travis CI build failed. Looks like an issue for generate docs where it is trying to execute a command with a list of dlls and failing because it is an empty list. Unclear to me at the moment why paket update broke this.

https://travis-ci.org/fsharp/FAKE/builds/571432477?utm_source=github_status&utm_medium=notification
```
could not parse [|"metadataformat"; "--generate"; "--outdir"; "./docs/apidocs/v5/legacy";

    "--layoutRoots"; "./help/templates/legacy"; "./help/templates";

    "./help/templates/reference"; "--sourceRepo";

    "https://github.com/fsharp/FAKE/blob/master"; "--sourceFolder";

    "/home/travis/build/fsharp/FAKE"; "--parameters"; "api-docs-prefix";

    "/apidocs/v5/legacy/"; "CurrentPage"; "APIReference"; "page-description";

    "FAKE - F# Make"; "page-author";

    "Steffen Forkmann, Mauricio Scheffer, Colin Bull, Matthias Dittrich";

    "project-author";

    "Steffen Forkmann, Mauricio Scheffer, Colin Bull, Matthias Dittrich";

    "github-link"; "https://github.com/fsharp/FAKE"; "version";

    "5.15.5-alpha.local.1"; "project-github"; "http://github.com/fsharp/FAKE";

    "project-nuget"; "https://www.nuget.org/packages/FAKE"; "root";

    "https://fake.build"; "project-name"; "FAKE - F# Make"; "--dllfiles"|]

  missing required option 'dllFiles' or invalid option value
```

**Comment by matthid** [comment]
Thanks for looking into this! Sometimes it's really frustrating to get things working again after `paket update` ...

**Comment by matthid** [comment]
One problem might be that FSharp.Core no longer supports `netstandard1.6` and we still build some stuff for `netstandard1.6`. I'll take a look

**Pull request merged**
