### PR TITLE
feat: basic features for GitHub Actions integration

### PR DESCRIPTION
**Pull request by Bomret**
### Description

Provides basic constructs for GitHub Actions support.

## TODO

Feel free to open the PR and ask for help

- [x] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
    - just static helpers, no logic
  
> Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [x] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [x] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [x] (if new module) the module is in the correct namespace
- [x] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [x] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by Bomret** [comment]
Hm, don't know exactly why the buil fails. Seems the appveyor file does not set up the correct dotnet core runtime?

**Comment by matthid** [comment]
@Bomret Thanks for this, please try to pull the latest release/next changes. This failure was due to the removal of preinstalled dotnet versions on appveyor and is fixed on the latest `release/next` changes.

**Comment by Bomret** [comment]
oof, I'll do a fresh fork and open a new PR.

**Comment by matthid** [comment]
Why? Did merging not went through?

**Comment by Bomret** [comment]
I had a very old state of the repo from ~5 years back. The PR suddenly had more than 100 changed files after merging in the latest release/next.

**Pull request closed without merging**
