### PR TITLE
Update Paket.Core to (better) support net5.0

### LINKED ISSUE #2555: Fake doesn't support new net5.0 patforms like net5.0-windows
### Description

When you use Paket to define build script dependencies and you restrict framework for net5.0-windows then paket won't be able to execute

### Repro steps

Create a solution that is managed by paket and fake and contains net5.0-windows project

1. Put in paket.dependencies restriction to net5.0-windows

2. Paket install

3. try build it using fake

### Expected behavior

It compiles

### Actual behavior

Error like this appears:
There was a problem while setting up the environment:
-> Error during parsing of 'C:\pathToYourFolder\paket.lock'.
-> invalid parameter 'net5.0-windows7.0' after >= or < in '== net5.0-windows7.0) (== net50)'

### Related information 

* Error occurs on Fake 5.20.4-alpha.1642
* I expect creating new version of Fake with latest Paket should fix this

### PR DESCRIPTION
**Pull request by pchinery**
### Description

With the current release of Fake, I receive this error when targeting net5.0:

```
There was a problem while setting up the environment:
-> Error during parsing of 'D:\Projekte\pdfcreator-online\cs-middleware\paket.lock'.
-> invalid parameter 'net50' after >= or < in '== net50'
```

It was suggested in #2555 that this could be fixed by updating the integrated Paket.Core and this indeed work for me. With the compiled result, I can run my build again.

- fixes #2555

### CODE REVIEW

**Comment by pchinery** [comment]
For some reason, the CI is failing, but if I'm looking right, this was the case in the main branch as well. I don't want to sound pushy, but I'm depending on a new release with my current work, so if there is anything I can do to speed up things I'd be happy to.

**Comment by matthid** [comment]
@pchinery Thanks for the PR, see https://github.com/fsharp/FAKE/issues/2544 and https://github.com/fsprojects/Paket/issues/3921
Do we now actually have stable packages for .net 5 or are they still "-rc"?

**Comment by matthid** [comment]
Is the current prerelease not working for you?

**Comment by mk185147** [comment]
> Is the current prerelease not working for you?

if you mean 5.20.4-alpha.1642 then it doesn't work, it has the bug #2555. The pull request #2544 was before the latest changes to support .NET 5 subplatforms in paket like fsprojects/Paket#3942 or fsprojects/Paket#3933

**Comment by mk185147** [comment]
Can we run the build again as it seems like an infrastructure error (System.Net.WebException: The remote server returned an error: (400) Bad Request.)? thanks

**Comment by pchinery** [comment]
> Is the current prerelease not working for you?

I'm sorry, I thought that I had answered, but obviously I did not. I have not been aware of how to use pre-release versions of locals tools, but after your remark, I have updated fake-cli to the latest alpha and it does solve my problem, so thank you for sending me in the right direction!

It probably still makes sense to update Paket.Core to the latest versions, even though I don't know to which extent the .net 5 support was improved in the meantime, but it appears to be pretty dynamic right now.

**Comment by mk185147** [comment]
net5.0 target works with current preview but net5.0-windows target doesn't

**Review by mk185147 — APPROVED** [review]
I like it

**Comment by BlythMeister** [comment]
Is it possible to get this shipped.  Though not perfect, it adds some support for net5 and means that people can start using it in some cases?
The issue i have is that as soon as net5 is added, the build pipeline falls in a heap.

**Comment by mexx** [comment]
fixes #2564

**Review by bughana — APPROVED** [review]

**Comment by bengobeil** [comment]
@matthid 

Hi Mattias,

Anyway we can get this merged? If you feel it's good to go, of course. It seems like a straight forward fix.

I think this can unblock many people.

Thanks,
Ben

**Comment by matthid** [comment]
@bengobeil the problem is not this change, but that the build went red because of some change in the environment. I'm not releasing with a red build. Additionally, on every release some maintenance work is needed (like release notes and stuff).
Another recent thing is: `FSharp.Formatting` (or the docs here) needs an update and quite a lot changed there as well.
The ecosystem is just moving and I lost interest with playing catchup ;)

Also, a lot of PRs in FAKE are newcomers in F# or quick hacks for some new use cases or something that changed somewhere else (new arguments or stuff like that). While I trust the current test coverage, I'd like to keep it that way (at least for as long as nobody else emerges as maintainer). This on the other side means additional maintenance to make sure changes meet the quality bar (reviews, writing tests, testing stuff if needed).

**Pull request merged**
