### PR TITLE
Find yarn.cmd more reliably on Windows

### PR DESCRIPTION
**Pull request by zakaluka**

### CODE REVIEW

**Comment by matthid** [comment]
Does this break people using the `Yarnpkg.js` package? Is that OK? Is that obsolete?

**Comment by zakaluka** [comment]
According to https://www.nuget.org/packages?q=Yarnpkg.js, there is no `Yarnpkg.js`.  

Searching for `Yarnpkg` only (https://www.nuget.org/packages?q=Yarnpkg), there is only 1 hit (the one I am accounting for here - Yarnpkg.Yarn).

**Comment by zakaluka** [comment]
Please note that there is no `Yarnpkg.js` on the `npm`-side either.

**Comment by zakaluka** [comment]
Updated to work with any package providing `yarn.cmd`.

**Comment by zakaluka** [comment]
As of now, if there is no package (or system-wide install) of `yarn.cmd`, the code will throw an error.  I believe this is correct behavior as we want the build to fail.

**Comment by matthid** [comment]
Is this now resolved since we have https://www.nuget.org/packages/Fake.JavaScript.Yarn ?

**Comment by matthid** [comment]
Closing as it at least would need a merge/rebase and cannot be merged currently.
Sorry for the slow reaction time / bad experience. This PR hit into a time with a lot of changes coming in.

**Pull request closed without merging**
