### PR TITLE
added Alias and HiddenTarget.

### PR DESCRIPTION
**Pull request by pms1969**
- Alias allows dependencies trees to be constructed and run as if they were defined that way.
- HiddenTarget just leaves the Target out of the listTargets and PrintTargets, allowing for a cleaner target list that doesn't include things you might not want to run directly.

### CODE REVIEW

**Comment by pms1969** [comment]
No idea how to write unit tests for these changes.  looked all thru the test project, but couldn't find any targethelper tests to add too.

**Comment by pms1969** [comment]
I don't understand the AppVeyor error. :-s  I've obviously done something a bit squiffy...  Any ideas?

**Comment by forki** [comment]
No appveyor was broken before. Will look into this tomorrow

**Comment by pms1969** [comment]
Sorry, I know you're busy.  Any progress?

**Comment by forki** [comment]
I'm not yet convinced that this is a good idea. Still thinking about it. Especially the ==> inside of targets is scary.

**Comment by pms1969** [comment]
That's fair enough.  i know it works very well, as that's how I use it, but maybe some other mechanism to do the same thing?  Say Alias equates to *=> which then trails on the rest of the chain, and this isn't evaluated until it tries to run the alias?

**Comment by pms1969** [comment]
I've found a better way of expressing what objective I'm trying to accomplish with this.

In Rake, you have tasks, and they can have dependencies.  like this 
`
task 'buildthing' => "prebuildthing" do
  puts "building"
end
`
so every time that "buildthing" gets called, it makes sure that prebuildthing is run before it.  Fake has the equivalent using the `==>` and `=?>` syntaxes.  I prefer the Fake implementation, because it allows for those dependency chains to be gathered in one place, and it makes tracking them down where a dependency chain is breaking down much easier

Rake also has dependency lists.  Like so:`task :go => [:first, :second, :buildthing, :postbuildthing]`

This creates a target that describes a chain of other targets that should be called when it is called, and will also inject any of their dependencies.  so in our example here, that means that when `:go` is invoked, it will call `:first => :second => :prebuildthing => :buildthing => :postbuildthing`.  As it stands this is what I'm trying to achieve by describing my task dependencies within another task.

**Comment by matthid** [comment]
I guess the same can be achieved via https://github.com/fsharp/FAKE/pull/920 (http://fsharp.github.io/FAKE/soft-dependencies.html). Let me know if I miss something and we can re-open this.

**Pull request closed without merging**
