### PR TITLE
Fix #1966

### LINKED ISSUE #1966: The release of System.Reactive 4.0 breaks `dotnet fake`
### Description

Following the [new release](https://www.nuget.org/packages/System.Reactive/4.0.0)  at ~17:00UTC Friday 25 May, builds from clean have stopped working.  In each case the script fails with
```
-> Could not load 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
   Full framework assemblies are not supported!
   You might try to load a legacy-script with the new netcore runner.
   Please take a look at the migration guide: https://fake.build/fake-migrate-to-fake-5.html
```

### Repro steps

Install Fake RC 16-225, then `dotnet fake run` this script

```
#r "paket:
nuget Fake.Core.Target prerelease
nuget Fake.Core.Environment prerelease
nuget Fake.Core.Process prerelease
nuget Fake.DotNet.AssemblyInfoFile prerelease
nuget Fake.DotNet.Cli prerelease
nuget Fake.DotNet.MSBuild prerelease
nuget Fake.DotNet.NuGet prerelease
nuget Fake.DotNet.Testing.NUnit prerelease
nuget Fake.DotNet.Testing.OpenCover prerelease
nuget Fake.DotNet.Testing.XUnit2 prerelease
nuget Fake.IO.FileSystem prerelease
nuget Fake.Testing.ReportGenerator prerelease //"

open System
open System.IO
open System.Xml
open System.Xml.Linq

open Fake.Core
open Fake.Core.Target
open Fake.Core.TargetOperators
open Fake.DotNet
open Fake.DotNet.AssemblyInfoFile
open Fake.DotNet.NuGet.NuGet
open Fake.DotNet.Testing.NUnit3
open Fake.Testing
open Fake.DotNet.Testing
open Fake.IO
open Fake.IO.FileSystemOperators
open Fake.IO.Globbing.Operators
open Fake.IO.Globbing.Tools

let Target s f =
  Description s
  create s f

// Preparation

Target "Preparation" ignore

Description "ResetConsoleColours"
let resetColours = (fun _ ->
  System.Console.ResetColor()
)
createFinal "ResetConsoleColours" resetColours
activateFinal "ResetConsoleColours"

Target "All" ignore

"Preparation"
==> "All"

runOrDefault "All"
```

### Expected behavior

Nothing much happens

### Actual behavior

```
Script reported an error:
-> FileLoadException: Could not load file or assembly 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. General Exception (Exception from HRESULT: 0x80131500)
   StackTrace:
        at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args)
        at Fake.Core.TargetModule.runOrDefault@818.Invoke(Boolean singleTarget, Int32 parallelJobs, FSharpList`1 arguments) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 819
        at Fake.Core.TargetModule.runWithDefault$cont@778-1(Boolean allowArgs, FSharpFunc`2 fDefault, FSharpMap`2 results, Unit unitVar) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 810
        at <StartupCode$Untitled-1_2FCFAC21BA7B45BC653F44FF9B5C2614F4ACF0473B9CBFCD2C21EE75219837AF>.$Untitled-1$fsx.main@() in C:\Users\steve\Documents\GitHub\altcover\Untitled-1.fsx:line 54
-> Could not load 'System.Reactive.Linq, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
   Full framework assemblies are not supported!
   You might try to load a legacy-script with the new netcore runner.
   Please take a look at the migration guide: https://fake.build/fake-migrate-to-fake-5.html
   StackTrace:
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
        at Fake.Runtime.CoreCache.findAndLoadInRuntimeDepsCached@274.Invoke(AssemblyLoadContext loadContext, AssemblyName name, VerboseLevel logLevel, FSharpList`1 runtimeDependencies) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 280
        at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
        at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

### Known workarounds

None yet

### Related information 

Observed on both Windows (AppVeyor) and Linux (travis-ci)

### PR DESCRIPTION
**Pull request by kblohm**

### CODE REVIEW

**Comment by kblohm** [comment]
@matthid I probably have to add the restricted System.Reactive to the packet.references aswell, right?

**Comment by matthid** [comment]
I think this is exactly what we should do, thanks for taking care of this. Will try to release this now :)

**Comment by kblohm** [comment]
IMO the underlying problem is that paket does not really handle the dependencies as expected if you use dotnet pack. Or is that by design? I could also not just get it to work with dotnet pack by adding a paket.template. Should we switch FAKE to use Paket.pack? (although that does not directly help in this exact case, but it would at least not screw up dependencies that FAKE defines)

**Comment by matthid** [comment]
Good point. I'm not sure if that ever worked :).
However, if that is indeed the expected behavior we can change how `dotnet pack` works (as we call `paket fix-nuxpec` in that scenario and can basically modify the nuspec as we please, we could even consider an existing `paket.template`)

**Comment by matthid** [comment]
https://github.com/fsprojects/Paket/issues/2883

**Comment by kblohm** [comment]
I am not sure if everybody expects it to work this way. But as i looked into the `paket.dependencies` for `FSharp.Control.Reactive` and saw that is did specify to use `System.Reactive ~> 3.0` i was kind of surprised that the restriction for a version < 4.0 was not in the actual nuget package. IMO this way paket is not really that "useful" if you plan to publish nuget packages with it. Everything paket does to handle your dependencies properly is suddenly lost if you publish your code. I dont even think i would require a `paket.template` the same way `dotnet pack` does not require a `.nuspec` anymore.

**Comment by matthid** [comment]
@kblohm Yes I talked with @forki and he agreed that we should fix the defaults here (ie by default take the ranges from the dependencies file).
Just note that there are cases where you want to "break" out of this behavior, because you might want to test/build with a bugfix release and want your final package to allow lower or higher version ranges.

**Comment by kblohm** [comment]
Sure, but thats what the optional paket.template could be used for right? Or make it a parameter if that is possible. It would be great if the default would just "work" for the 90% case. 👍

**Comment by matthid** [comment]
exactly

**Pull request merged**
