### PR TITLE
Enhancements to Fake.Core.Xml

### PR DESCRIPTION
**Pull request by BlythMeister**

### CODE REVIEW

**Comment by matthid** [comment]
The error is a bit hard to find in the CI:
`[00:09:39] C:\projects\fake-6w516\src\app\Fake.Core.Xml\Xml.fs(119,9): error FS0041: No overloads match for method 'Load'. The available overloads are shown below. [C:\projects\fake-6w516\src\app\Fake.Core.Xml\Fake.Core.Xml.fsproj]`

I guess you need a type annotation somewhere.

**Comment by BlythMeister** [comment]
Oh yeah, 4 signatures on load.

**Comment by BlythMeister** [comment]
@matthid this one should be good now

**Comment by BlythMeister** [comment]
🎉 it builds 😄

**Comment by matthid** [comment]
Sad that we missed the `[<RequireQualifiedAccess>]` on the Fake.Core.Xml module :/

**Comment by BlythMeister** [comment]
Too late to add it I guess without it being breaking...

**Pull request merged**
