### PR TITLE
Paket Update

### PR DESCRIPTION
**Pull request by BlythMeister**
### Description

* Update paket cli version in dependencies to 5.200.4
* Run paket update command

Required due to new setting in 5.200.4 from PR https://github.com/fsprojects/Paket/pull/3523

### CODE REVIEW

**Comment by matthid** [comment]
Typical paket update, everything broken

**Comment by matthid** [comment]
> ##[error]Fsc: D:\a\1\s\src\app\Fake.netcore\Program.fs(306,33): error FS0039: The constructor, module or namespace 'DNXCore' is not defined.

I think some minor code adjustments are required for the breaking changes in paket

**Comment by BlythMeister** [comment]
@matthid tbf...it was my change that broke the 1st thing....@forki was the other one :p

Have updated to remove DNXCore as that value no longer exists as an option :)

**Comment by matthid** [comment]
Thanks a lot for taking care of this :)

**Pull request merged**
