### PR TITLE
quote project parameters in dotnet module

### LINKED ISSUE #2052: DotNet Module does not quote project parameter
`DotNet.build`, `DotNet.publish`, `DotNet.test`, `DotNet.pack` and `DotNet.restore` do not quote the project parameter. Is this intended or can i do what the MsBuild module does and quote the parameter?

### PR DESCRIPTION
**Pull request by kblohm**
fixes #2052

### CODE REVIEW

**Comment by matthid** [comment]
I'm not sure if `quoteIfNeeded` is correct. It looks broken to me. Should we fix that here or use one of the new apis?

**Comment by kblohm** [comment]
That is the one used in the MsBuild-Module (and probably all over the place). Where can i find a version that is not broken?

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.Core.Process/CmdLineParsing.fs are the new apis for escaping arguments they conform to the spec. We always use the "windows" escaping (even on linux) as that's what they have implemented in netcore.

**Comment by matthid** [comment]
Also I'm not even sure why `quoteIfNeeded` actually exists, why not just always escape properly?

**Comment by kblohm** [comment]
I have no idea. Maybe unescaped arguments look better? ;)

**Comment by matthid** [comment]
I guess it's historic because we never had proper escaping and unquoted worked cross platform

**Comment by matthid** [comment]
Or leave it like this I think I'll just update `quote` and `quoteIfNeeded` and see what happens on next release

**Comment by kblohm** [comment]
Update it to delegate to the new API?

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/pull/2045/commits/109ec13f8813533bbefdb96c4e9b0518001029ad

**Comment by matthid** [comment]
Thanks!

**Pull request merged**
