### PR TITLE
Fake template cmd changes

### PR DESCRIPTION
**Pull request by florianbader**
### Description

Changes the bootstrapping of the fake template to provide a build.cmd/build.sh which directly calls _fake build_. For a beginner this is much easier and most projects which use FAKE later have a build batch script instead of a fake batch script anyway.

### CODE REVIEW

**Comment by florianbader** [comment]
I didn't want to open an issue to discuss this small change, so feel free to discuss if you want to change the bootstrapping method here.

**Comment by BlythMeister** [comment]
I personally have a "run.cmd" which is what we have in our repos.

**Comment by florianbader** [comment]
I guess I see your point. Maybe having a choice between fake.sh, build.sh and run.sh which defaults to fake.sh would be a nice solution for that. I just like the idea of a template which does all the work for me, which means I don't have to rename and rewrite the fake.sh because I don't care about _fake --help_ and I also don't have more than one build script.

**Comment by BlythMeister** [comment]
Fake isn't just for building though.  We use it for executing tests on deployed systems too.

**Comment by kblohm** [comment]
Then the name would not just change the command name but also add different behavior, right? That is somewhat confusing. It would add additional complexity for, in my opinion, very little gain. Especially because the template is somewhat of a "getting-started" help. It would also raises the question of what names to support. Is it just fake and build? Or fake or build and run? I think it is easy enough to rename those 2 files afterwards. We could maybe add an option to specify a generic filename, but i would not change the contents of those files.

**Comment by florianbader** [comment]
> Then the name would not just change the command name but also add different behavior, right? That is somewhat confusing. It would add additional complexity for, in my opinion, very little gain. Especially because the template is somewhat of a "getting-started" help. It would also raises the question of what names to support. Is it just fake and build? Or fake or build and run? I think it is easy enough to rename those 2 files afterwards. We could maybe add an option to specify a generic filename, but i would not change the contents of those files.

That's correct. If you are getting started though, I don't think you would pass any parameters and the default behavior stays the same as it is now. For everyone who is too lazy to rename and rewrite their scripts, they can just pass the right parameter. I don't see how that adds any more complexity than the other parameters the template currently has.

**Comment by matthid** [comment]
Closing, but I'm happy to continue the discussion or get a new suggestion

**Pull request closed without merging**
