### PR TITLE
extended CopyRecursive function

### PR DESCRIPTION
**Pull request by quezlatch**
an extended function CopyRecursive2, as files are copied into the destination directory they can be overwritten, not overwritten, skipped, included or excluded according to a wildcard pattern, or a function can be used to decide whether to copy or not

### CODE REVIEW

**Comment by matthid** [comment]
Can you try to send the PR on top of my matthid:coreclr branch? This would make sure your changes are not lost in the new netcore release (and you could use them right away from the AppVeyor nuget feed (https://ci.appveyor.com/nuget/fake).

Thanks!

**Comment by quezlatch** [comment]
@matthid i'm not sure what you mean by this. my git skills are still a work in progress i'm afraid... but certainly i'm happy to do this

**Comment by matthid** [comment]
@quezlatch Basically add my repository:

```
git remote add matthid https://github.com/matthid/FAKE.git
git fetch matthid
```

checkout the coreclr branch (and create a new branch out of it)
```
git checkout -b copydir_coreclr matthid/coreclr
```
Then just apply your changes. Note that the FileHelper is obsolete and your changes need to go to files in the `Fake.IO.FileSystem` directory (part of the FakeLib project). We are now in the happy situation that we can do breaking changes in this new API :)
Cleanup in that part is not jet done so feel free to do anything ;)

Once finished just push your branch to your fork and send a PR to my fork (you can select this stuff on the github website when creating the PR)

**Comment by quezlatch** [comment]
Ah right. Got you. So essentially create a new pr based on this. Will do. I'll close this one then

**Comment by matthid** [comment]
You can leave this one as is for now

**Comment by quezlatch** [comment]
ok. will do

**Comment by matthid** [comment]
I think it makes sense to feature stop the old code-base. You change was already merged into the new code-base https://github.com/fsharp/FAKE/commit/00046a2d02a2c8eafa43ff8eaeb2bcd023b924c5. I'm kind of nervous regarding the introduced dependency (as I carefully tried to prevent it previously). But I'l revisit that later. For now I don't think we need this PR anymore. Thanks for contributing!

**Comment by quezlatch** [comment]
ok. many thanks

**Pull request closed without merging**
