### PR TITLE
Apidoc fixes

### PR DESCRIPTION
**Pull request by JarnoNijboer**
### Description
This fixes some layout issues in the [api references](https://fake.build/apidocs/v5/index.html#Fake.Api)

This PR is based off latest master, since my guess was that you probably would push these changes without a new release.

* Namespace list was dropping of screen without scrolling. On small screens, you couldn't see the items that we're off screen
* Documentation tables take with of content rather than full width
* On screens `<= 768px` table was bigger than `100%`
* Added a padding of `5px` above scrollbar in code samples

### Big screens

Before:
image

After:
image

### Small screens
Scrollbars are not very visible
Before:
image

After:
image

### CODE REVIEW

**Comment by matthid** [comment]
I assume you have tested this on very small browser-width's and mobile as well?

**Comment by matthid** [comment]
Thanks, will test this on staging after merging. I tried to figure that out but never found a setup with works in API-Reference AND the regular markdown code-boxes (prism) as well as the start-page

**Comment by JarnoNijboer** [comment]
I've tested on small screens as well, using devtools to simulate smaller viewports.

**Comment by JarnoNijboer** [comment]
My changes have broken the codesamples on the startpage. In a few moments I will push a fix for it.

**Comment by matthid** [comment]
Ok let's see how it looks, thanks!

**Pull request merged**
