### PR TITLE
Update FCS to circumvent MethodNotFound Exception

### PR DESCRIPTION
**Pull request by baronfel**
### Description

Versions of FCS greater than 34.0.1 introduced overloads of FSharpChecker.Create that have new optional arguments. This means that the usage of FSharpChecker.Create in the Yaaf Scripting file not longer target the same method and so the underlying FCS reference needed to be updated.

This PR performed this update.

- fixes https://github.com/fsharp/FsAutoComplete/issues/561

## TODO

- [x] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)

### CODE REVIEW

**Comment by matthid** [comment]
Thanks! By the way: Does this already include the #r nuget feature?

**Comment by baronfel** [comment]
It includes the base infrastructure, but we don't currently distribute the built-in Nuget provider that actually handles the nuget resolution.  There are still open questions about how that distribution would be handled, IMO.  

There's enough here to build and use with a Paket-plugin, for example.

**Comment by matthid** [comment]
Ok, we can handle that feature later. I'll try to get out at least an alpha package so we can fix ionide.

**Comment by matthid** [comment]
@baronfel You can use `5.19.2-alpha.1526` in a couple of minutes. Let me know if it works (I think it is fine to use the alpha in ionide as it has the same quality bar as a regular release)

When it works I'll probably release 5.20 tomorrow.

**Pull request merged**
