### PR TITLE
Added first cut of an IncrementalHelper.fs

### PR DESCRIPTION
**Pull request by bradphelan**

### CODE REVIEW

**Comment by mavnn** [comment]
@bradphelan I started playing with a more in depth implementation of this at https://github.com/FakeShake/Fake.Shake (replaces the dependency tree as well as built in incremental builds).

Want to compare notes / try and keep the caches compatible if possible?

**Comment by bradphelan** [comment]
I'm not really actively developing this. I just got motivated to submit it cause every few month or so, somebody posts how Fake is better than some Make derivative without realizing what Fake is missing and how it is a bit difficult to get right. If you see anything in my code you want to steal then go for it. I'll try to get around to reading the Shake paper. Looks interesting. I suspect it is theoretically more robust than my solution if it's coming from a bunch of Haskel devs.

**Comment by matthid** [comment]
Is this kind of related to https://github.com/fsharp/FAKE/pull/894 ?

**Comment by matthid** [comment]
I think this is kind of related to what xake/shake are trying to achieve. In particular I think it is outdated now.

**Pull request closed without merging**
