### PR TITLE
[WIP] Fake netcore foundation

### PR DESCRIPTION
**Pull request by cloudRoutine**
@forki  no conflicts to worry about 😉 

At this point.... 

- Should I keep working from this and try to unify the two different sides of FAKE?
- Should there be parallel implementations for netcore and netframework?
- Fork off of this PR branch into a new repo for #NewProduct ?
- Something else....?

### CODE REVIEW

**Comment by matthid** [comment]
@cloudRoutine I think for this to work we need to do the following:

 - [ ] make this green
 - [ ] merge
 - [ ] don't accept PRs which update legacy code anymore
 - [ ] release the new API
 - [ ] start to build the compat layer and replace the old release

Otherwise we will never catch up.

**Comment by forki** [comment]
+45,859 −1,069

**Comment by matthid** [comment]
@forki Yes because of compat, we hopefully will be able to remove a lot of stuff in the future once we managed the transition.

**Comment by forki** [comment]
good to hear. How safe is to merge it? How much would we break?

**Comment by cloudRoutine** [comment]
let's wait until it's green, I'll take a look at it later tonight or tomorrow

**Comment by matthid** [comment]
@forki 

> good to hear. How safe is to merge it? How much would we break?

Nothing, those are separate code bases for now. But we could poke PRs to update the new code base as well (Phase 1). And get better diffs...
Only problem is that our build time is currently really bad...

> let's wait until it's green, I'll take a look at it later tonight or tomorrow

Thanks @cloudRoutine. I took a quick look again and send a small update (though still not green)

**Comment by matthid** [comment]
One open problem is https://github.com/fsharp/FSharp.Compiler.Service/issues/715 not sure if we should add a workaround for now...

**Pull request closed without merging**
