### PR TITLE
Fake 5.1.0

### PR DESCRIPTION
**Pull request by matthid**
Todo update obsolete warnings in dotnetcli module

### CODE REVIEW

**Comment by matthid** [comment]
@kblohm The `fake-template`-package is somehow missing from staging myget feed. I guess we need to change `build.fsx` somewhere in order to push it...

**Comment by kblohm** [comment]
Just out of curiosity, did to add the `.proj` by hand or with vs or did you mange to get the cli to do it?

**Comment by matthid** [comment]
@kblohm As suggested I renamed to `.fsproj` and did `dotnet sln Fake.sln add ...` (actually I didn't even try with `.proj` and assumed it wouldn't work)

**Comment by kblohm** [comment]
Oh, i did not see the rename. Ups.
Thanks for taking care of this 👍 .

**Comment by matthid** [comment]
I'm glad we have the staging area now :D I always miss something apparently

**Comment by kblohm** [comment]
Yes, thats actually quite useful :).
About the `Fake.All` package, should i open an issue for discussion? Or just make a PR to create one when i have the time?

**Comment by matthid** [comment]
everything seems to work :)

**Comment by matthid** [comment]
> Or just make a PR to create one when i have the time?

Yeah feel free to make PR. I'm just not completely sure if we should recommend such a package or not.

**Comment by matthid** [comment]
I guess we somewhere have set 1minute and the download on gitlab is a bit slower?

Also any idea why one test is ignored?

**Comment by baronfel** [comment]
One test is ignored because it's using the tool version of the template with the local install, but as discussed in the template PR that variant is broken entirely because the local tool install paths are wrong (dotnet cli issue, not fake.sh issue).

The timeouts on the other tests may just need to be lengthened for CI, maybe package restore is longer there?

**Pull request merged**
