### PR TITLE
iOSBuild relies on xbuild instead of mdtool

### PR DESCRIPTION
**Pull request by molinch**
iOSBuild relies on xbuild instead of mdtool (Xamarin pushes to use xbuild instead of mdtool).

This implies some changes for iOSBuild parameters:
- Configuration only contains the configuration now (Debug, Release, Adhoc, AppStore) and no longer the platform. This is an additional property called Platform (iPhone vs iPhoneSimulator)
- BuidlIpa true/false to indicate wether you want an IPA file to be produced

### CODE REVIEW

**Comment by molinch** [comment]
@gshackles As said on Twitter this is the PR.

**Comment by thomasvdb** [comment]
Great!
If the pull request is merged, the issue #940 can be closed.

**Comment by forki** [comment]
thx a lot

**Comment by thomasvdb** [comment]
Having a strange issue with the location of the IPA file.
If I specify the OutputPath to, for example, C:\Projects\iOS\ then all the sources are placed inside that folder during the build but the IPA file is placed one directory higher (C:\Projects in the example).

Any idea what the issue could be?

**Comment by molinch** [comment]
Absolutely no idea, we don't use this parameter on our side. Does it behave correctly with android builds?

**Pull request merged**
