### PR TITLE
Update canopy and IIS docs

### PR DESCRIPTION
**Pull request by jwood803**
Adds a bit more detail to let users know that FAKE.IIS is a separate package to be installed.

### CODE REVIEW

**Comment by forki** [comment]
Why would Canopy require fake.iis?

**Comment by jwood803** [comment]
In the example given in the doc on the Canopy page FAKE.IIS is needed or the `createConfigFile` and the `HostWebsite` functions.

**Comment by forki** [comment]
Ah Ok. Maybe you can clarify this even a bit more then. Thanks

**Comment by jwood803** [comment]
Sure, I'll update it

**Comment by jwood803** [comment]
Updated some of the verbiage that should make it a bit clearer on the user of FAKE.IIS

**Comment by forki** [comment]
thx

**Pull request merged**
