### PR TITLE
Add a recursive directory copier so that the bin folder and all subdi…

### PR DESCRIPTION
**Pull request by wooderz**
…rectories are copied, not just the bin files.

### CODE REVIEW

**Comment by matthid** [comment]
@wooderz thanks!
Can you send the change to https://github.com/fsharp/FAKE/tree/master/src/app/Fake.DotNet.MsBuild as well? Also if possible re-use existing helpers. I think we have directory copy already (at the very least it needs to be private)

**Comment by wooderz** [comment]
Hi @matthid 
No problem, can you point me to the helper that already exists? I did look but was unable to find one!

Cheers

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/blob/master/src/app/Fake.IO.FileSystem/FileSystem.fs#L118 `DirectoryInfo.copyRecursive`?

**Comment by matthid** [comment]
Closing due to inactivity. Please feel motivated to open a new one based on the latest code.

**Pull request closed without merging**
