### PR TITLE
WIP: Debian packaging

### PR DESCRIPTION
**Pull request by TheAngryByrd**
This PR creates initial support for creating fake packages with fpm.  

I removed ubuntu specific runtime ids and replaced it with the linux one.  If there's a reason to go back let me know.

Testing so far: 

* [Install FPM](https://semicomplete.com/projects/fpm/1.6/installing.html)
* Run `DotNetCoreCreateDebianPackage` target on osx/linux 
  * `dotnet fake build -- -t DotNetCoreCreateDebianPackage`
* Install on debian based distro
  * `sudo dpkg -i fake_5.0.0~rc004_amd64.deb ; sudo apt install -f -y`

Things left to do

- [ ] Clean up code
- [x] TravisCI creating packages
- [ ] Discuss hosting options (could punt to another issue/PR)

### CODE REVIEW

**Comment by matthid** [comment]
For we could just upload the dep file to github releases and discuss hosting separately. At least it improves the situation a bit.

Regarding running on linux that is a bit of a problem as we currently release on windows (and I'd like to prevent running a release on multiple machines as of today). If we cannot get fpm to run on windows we might need to use docker or something like that.

**Comment by TheAngryByrd** [comment]
is linux subsystem an option? if not, I can see if I can get fpm working on cygwin/babun also if that's on the table.

**Comment by matthid** [comment]
> is linux subsystem an option?

We are planning to switch to a deployment pipeline (instead of releasing locally). I'm not sure if it is available there.

>  if not, I can see if I can get fpm working on cygwin/babun also if that's on the table.

Yes that would make me feel a bit better. In worst case we can probably bundle everything (for example as nuget package).

**Comment by matthid** [comment]
Just to let you know: I'm currently thinking about introducing a release pipeline for fake. And it is possible that I decide to use gitlab ci, which would mean fpm is available...

**Comment by matthid** [comment]
Ok our release process is not setup with vsts. In theory we could use linux agents. But stuff would be a lot simpler if we manage to run it on windows somehow ...

**Comment by TheAngryByrd** [comment]
If we hard need it to run on windows, I'll poke around the dotnet-packaging stuff and see if that's usable.

**Comment by TheAngryByrd** [comment]
As I was screwing around I found there was already a `fake` package listed in debian repos https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=fake

Should we rename to `fake-cli`?

**Comment by matthid** [comment]
> Should we rename to fake-cli?

Yeah I guess we need to? At least it matches with global tool. Question is if we should rename chocolatey :)

**Comment by TheAngryByrd** [comment]
Technically haven't released officially yet so a name change is fine right? 

I'll leave this decision up to you :)

**Comment by matthid** [comment]
Apparently that dotnet-packaging stuff breaks the regular publish process. Maybe we just need to copy the project file once mode (we already have copies for `dotnet-fake` and `fake-cli`...)

**Comment by TheAngryByrd** [comment]
Sorry I take a look at this tonight.

**Comment by TheAngryByrd** [comment]
This is green now, anything obvious that need to change?

**Comment by matthid** [comment]
Please give me a couple of days to review, but if this works and the integration in the release process works (for example upload to github) then it should be fine. Thanks a lot will report back in detail soon (hopefully)

**Comment by matthid** [comment]
Ok can you please add the generated `.dep` file to the github release:

https://github.com/TheAngryByrd/FAKE/blob/2b24412e9a4ac6f9ee67415ffabf20b9767e7b8a/build.fsx#L1215-L1224

I think adding it here (FastRelease Target) should be enough

**Comment by matthid** [comment]
Ok let me try to finalize this, thanks!

**Comment by matthid** [comment]
The debian package is already on github-staging, see https://github.com/fake-staging/FAKE/releases

Feel free to test

**Comment by matthid** [comment]
Do we need some documentation around how to use this?

**Comment by TheAngryByrd** [comment]
Sorry, just saw this. Anything else for me to do?

> Do we need some documentation around how to use this? 


For installing

```
1. Download fake-cli.5.1.1.linux-x64.deb (or appropriate version)
sudo dpkg -i fake-cli.5.1.1.linux-x64.deb ; sudo apt install -f -y
```

Running should be the same after that. 

`fake build`

**Pull request merged**
