### PR TITLE
Don't show the obsolete usage.

### PR DESCRIPTION
**Pull request by matthid**
Maybe don't event advertise the old usage in the CLI :). See https://github.com/fsharp/FAKE/pull/1090

### CODE REVIEW

**Comment by forki** [comment]
thx

**Comment by bentayloruk** [comment]
I thought the same.  Happy to pull it out if everyone thinks it's OK.

**Comment by forki** [comment]
I think we should remove the message for now and reevaluate the parser.

**Comment by bentayloruk** [comment]
@forki I'm hoping this is just confusion about the two CLIs and the parser is fine, but we'll see when you try this https://github.com/fsharp/FAKE/pull/1090#issuecomment-173547199 :grin: :8ball:

**Pull request merged**
