### PR TITLE
Add support for NUnit3 --params parameter

### PR DESCRIPTION
**Pull request by lefthandedgoat**

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
This fixes https://github.com/fsharp/FAKE/issues/1493

**Comment by matthid** [comment]
Can you try to send the PR on top of my matthid:coreclr branch? This would make sure your changes are not lost in the new netcore release (and you could use them right away from the AppVeyor nuget feed (https://ci.appveyor.com/nuget/fake). If you need help, let me know.

Thanks!

**Comment by lefthandedgoat** [comment]
@matthid I pulled your coreclr branch into my branch and I tried to build but it always get stuck.

These are the last lines before it gets stuck:

```
  Fake.DotNet.Testing.NUnit -> /Users/cholt1/projects/FAKE/src/app/Fake.DotNet.Testing.NUnit/bin/Release/netstandard1.6/Fake.DotNet.Testing.NUnit.dll
  0 seconds - ready.
  Successfully created package '/Users/cholt1/projects/FAKE/nuget/dotnetcore/Fake.DotNet.Testing.XUnit2.5.0.0-alpha004.nupkg'.
  Paket version 4.8.4
  0 seconds - ready.
  Successfully created package '/Users/cholt1/projects/FAKE/nuget/dotnetcore/Fake.DotNet.Testing.NUnit.5.0.0-alpha004.nupkg'.
```
I am using OSX and I dont even know if I have the latest .net core installed etc.

I also saw that the file I changed is marked as deprecated.  I am happy to make the change in the new file also, but I can't build =\.

**Comment by matthid** [comment]
@lefthandedgoat oh... I think its enough to ignore that (for now) and just add your changes to the new file. If you open the solution you will see a folder like `Fake.DotNet.Testing.NUnit` in FakeLib that's where the new stuff is. No .net core is required. If it doesn't compile for .net core (you changes don't looke like it) I'll handle that.

**Comment by forki** [comment]
thx

**Pull request merged**
