### PR TITLE
retrieve mono version and ignore caching on mono 5.0.0

### PR DESCRIPTION
**Pull request by matthid**
Ok secound try...

### CODE REVIEW

**Comment by matthid** [comment]
@nosami :)

**Comment by nosami** [comment]
This works - apart from failing caching tests :)

**Comment by nosami** [comment]
```
13:01 $ mono ~/src/fake/build/FAKE.exe
We don't try to cache, see https://github.com/fsharp/FAKE/pull/1534
```

**Comment by matthid** [comment]
> This works - apart from failing caching tests :)

Well you tested it, that's enough for me :)

**Comment by nosami** [comment]
Still need to investigate the cause of this System.Reflection.Emit.ModuleBuilder.Save bug. Once that's fixed, we can revisit

**Comment by nosami** [comment]
Can't repro with this standalone script
```fsharp
#r "FSharp.Compiler.Service.12.0.5/lib/net45/FSharp.Compiler.Service.dll"
open Microsoft.FSharp.Compiler.Interactive.Shell

open System.IO
open System.Text

// Intialize output and input streams
let sbOut = new StringBuilder()
let sbErr = new StringBuilder()
let inStream = new StringReader("")
let outStream = new StringWriter(sbOut)
let errStream = new StringWriter(sbErr)

// Build command line arguments & start FSI session
let argv = [| "C:\\fsi.exe" |]
let allArgs = Array.append argv [|"--noninteractive"|]

let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration()
let fsiSession = FsiEvaluationSession.Create(fsiConfig, allArgs, inStream, outStream, errStream)  
let script =
    """
    open System
    type MyAttr() =
      inherit Attribute()
      do failwith "test"
    
    [<MyAttr()>]
    type Test () =
      do ignore ()
    [<assembly: MyAttr()>]
    do ()
    """
fsiSession.EvalScript script
let builder =
    match fsiSession.DynamicAssembly with
    | :? System.Reflection.Emit.AssemblyBuilder as builder -> builder
    | _ -> failwith "The DynamicAssembly property is no AssemblyBuilder!"
builder.Save("FSI-ASSEMBLY.dll")
```

**Comment by matthid** [comment]
@nosami Can you try with the `Yaaf.FSharp.Scripting` API, which is a small layer on top of FCS? (https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs) It executes some other sanity stuff before.

Do you compile and run the standalone script or run it via fsi?
There are some other subtle differences but I guess its one of those that matter...

**Comment by nosami** [comment]
I was running it via fsi. Currently working on a repro with Yaaf.FSharp.Scripting

**Comment by matthid** [comment]
You can see how the API is used here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L459

Thanks for taking care :)

**Comment by matthid** [comment]
Running via fsi makes a difference as then another `FSharp.Core` is loaded and you have another environment...

**Comment by nosami** [comment]
Weirdly, it doesn't repro in a console exe or using Yaaf.Scripting with default options

**Comment by matthid** [comment]
Well its a runtime crash, it can be the special way we setup our environment or a timing thing or any combination :/. Maybe it depends on the size of the stack at runtime...

**Comment by matthid** [comment]
(In other words I don't have another idea anymore ;) )

**Comment by nosami** [comment]
Yeah.. no worries - will keep digging

**Comment by matthid** [comment]
You can only really go the other way: Start with the FAKE code and reduce the code until the error disappears :)

**Comment by nosami** [comment]
Fixed by https://github.com/mono/mono/pull/4769

**Pull request merged**
