### PR TITLE
Support for F# SDK 10.1

### LINKED ISSUE #1855: executeFSIWithArgs fails because it can't find fsi
In FSharp.Data, `executeFSIWithArgs "docs/tools" "generate.fsx"` started failing with `System.Exception: Start of process fsi.exe failed. The system cannot find the file specified` (https://github.com/fsharp/FSharp.Data/issues/1142)

This was either due to the upgrade from FAKE 4.64.4 to 4.64.11, or due to the upgrade to the F# SDK 10.1 SDK which has a different path structure

Executing the file inside VS or VSCode works fine though, it only fails when running from the command line with `packages\FAKE\tools\FAKE.exe build.fsx` (which is done by build.cmd)

### PR DESCRIPTION
**Pull request by ovatsus**
closes #1855

### CODE REVIEW

**Comment by ovatsus** [comment]
Would be great if you could release this soon

**Comment by matthid** [comment]
I already pinged @forki . Problem is that I never managed to get the fake 4 release working on my system :/

**Comment by matthid** [comment]
@ovatsus First step of the migration (ie upgrading to the 5.0 nuget package) should be harmless in any case. If not that would be a bug. But you will get a lot of warnings ;) - which could be disabled via `fsiargs`

**Comment by matthid** [comment]
And that still needs a working implementation first so... ;)

**Comment by ovatsus** [comment]
Ok, you were right, it was easy (https://github.com/fsharp/FSharp.Data/pull/1150), but yikes so many warnings. Why did everything change? :)

**Comment by ovatsus** [comment]
Now just need someone to fix all the warnings (hint hint :p) https://github.com/fsharp/FSharp.Data/issues/1151

**Pull request merged**
