### PR TITLE
Add a Vagrant file to automatically deploy an Ubuntu 14.04 development VM

### PR DESCRIPTION
**Pull request by bbenoist**
Mostly inspired from the existing Vagrantfile in [Math.Net Numerics](http://numerics.mathdotnet.com/).

See https://www.vagrantup.com/ for more information about the Vagrant software.

### CODE REVIEW

**Comment by bbenoist** [comment]
If you want to test the PR:

1. Install VirtualBox and the VirtualBox Extension Pack from [https://www.virtualbox.org/wiki/Downloads](https://www.virtualbox.org/wiki/Downloads) or with your favorite package manager ([which should respect the PUEL](https://github.com/NixOS/nixpkgs/issues/672#issuecomment-19901614) :tired_face:).
1. Install Vagrant from [https://www.vagrantup.com/downloads.html](https://www.vagrantup.com/downloads.html) or with your favorite package manager.
2. With an elevated PowerShell or CMD, `cd` to the FAKE root directory and run `vagrant up`. The VM will be automatically downloaded, imported into VirtualBox, configured and started.
4. Run `vagrant ssh` to directly connect via SSH to the VM and start working. The FAKE source directory is automatically shared with the VM under the `/vagrant` directory.
5. Once you have finished, you can either:
  * Run `vagrant suspend` to pause the VM.
  * Run `vagrant halt` to shutdown the VM.
  * Run `vagrant destroy -f` to delete the imported VM.
  * Run `vagrant box remove ubuntu/trusty64` to remove the base box from your computer.
6. Simply re-run `vagrant up` to reload the VM.

:warning: The file `build.sh` had `crlf` on Windows and I had to update the .gitconfig file to force the use of `lf`. You may need to change it manually on your local Git clone.

**Comment by forki** [comment]
What does this give us? I never used vagrant.

**Comment by bbenoist** [comment]
Well, Vagrant helps in the creation and configuration of lightweight, reproducible and portable development environments.

It places itself on top of most virtualization products (e.g. VirtualBox, VMware) and uses SSH or WinRM to leverage the provisioning (e.g. shell commands, puppet, chef) on booted virtual machines.

Thus, by writing a `Vagrantfile`, you can give developers the possibility to deploy an appropriate OS and configuration with only one `vagrant up` command.

As an example, here is how I managed to build FAKE on Ubuntu (I omitted the crlf issue with `build.sh` to be more concise):

1. Created a `Vagrantfile` template with `vagrant init ubuntu/trusty64`.
2. Edited the `Vagrantfile` to fit with the needs of F# development on Ubuntu 14.04 LTS. Mostly taken from [Math.NET Numerics](https://github.com/mathnet/mathnet-numerics).
3. Ran `vagrant up`. The tool automatically:
    * Downloaded the base box from the Vagrant public repository.
    * Imported it into VirtualBox.
    * Started it and waited for SSH to be accessible.
    * Connected via SSH to install the required tools.
4. Built FAKE with `vagrant ssh -c "cd /vagrant && bash build.sh"`

Because I created my Ubuntu development VM with a `Vagrantfile`, other people now just have to install the system-wide prerequisites then reproduce steps 3 and 4 to get an Ubuntu development environment ready.

Also, as everything is in a VM, they just have to `vagrant provision` or `vagrant destroy -f` whenever it has to be updated or gets updated.


IHMO, its biggest usage would be for Windows people testing their development on a *nix system. However it's use can be extended up to many other scenarios (more to come).

**Comment by forki** [comment]
ok cool

**Comment by bbenoist** [comment]
Nice :sunglasses: Dedicaded markdown documentation incoming...

**Pull request merged**
