### PR TITLE
add new grunt helper

### PR DESCRIPTION
**Pull request by dnauck**
A new helper for the js grunt task runner

### CODE REVIEW

**Comment by matthid** [comment]
I'd love to see this as fake 5 module (see contribution guideline for further information how to do it)

**Comment by forki** [comment]
But Daniel needs it for fake 4 ;-)

Am 05.09.2017 4:11 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
Then we need both and an additional pr on hotfix branch ;)

If we want to get away from that big thing it will not be easy...

**Comment by matthid** [comment]
ping :)

**Comment by matthid** [comment]
Closing due to inactivity. Please feel motivated to open a new one based on the latest code. We now have documentation and lots of modules to look into on how to do things.

**Pull request closed without merging**
