### PR TITLE
#1194 update fix for mono encoding in ProcessHelper.fs

### PR DESCRIPTION
**Pull request by alexsorokoletov**
to work in all scenarios.

This PR comes as fix for the incomplete pull request #1275 made by me previously.
Problem was that I made incorrect if statement inside another if and thus the encoding enforcement did not work correctly in all cases such as when called from GitHelper or HockeyAppHelper modules.

Apologies for that.

### CODE REVIEW

**Comment by forki** [comment]
thanks so much for taking care of this!

**Comment by alexsorokoletov** [comment]
@forki it's not yet working. Can you help me understand how do I test the locally built F# Fake without getting it into the nuget?

**Comment by alexsorokoletov** [comment]
I'm actually repeating steps of https://github.com/fsharp/FAKE/commit/3f33e8c47da28aef8855513359f723f55d002f33#diff-f3936af8db25ef04f3cd0ed22cbc36e5
(commit 2d63a45 regarding #1212 and #1213).

Probably the right way to do is to undo this stuff that I broke in and update specifically HockeyAppHelper and XamarinHelper and GitHelper if needed.

**Comment by forki** [comment]
you can run the build?!

**Comment by alexsorokoletov** [comment]
@forki I do.

**Pull request merged**
