### PR TITLE
Added basic support for creating Azure Cloud Services.

### PR DESCRIPTION
**Pull request by isaacabraham**
Using this locally, all works fine for a single role cloud service. Feedback appreciated.

### CODE REVIEW

**Comment by forki** [comment]
very cool. thanks

**Comment by TWith2Sugars** [comment]
Nice, this will come in very useful for me.

**Comment by forki** [comment]
Would be awesome if we would have a tutorial for this as well.

**Comment by isaacabraham** [comment]
@TWith2Sugars it's pretty basic at the moment - it assumes you've already done an MSBuild, and assumes that the svcdef is called ServiceDefinition etc.., but it's working for me :-)

@forki ok - if I were to do one would you just want me to add to the docs in the source (that pushes out to the github website)?

**Comment by forki** [comment]
you could copy and edit https://github.com/fsharp/FAKE/blob/master/help/azurewebjobs.md

**Pull request merged**
