### PR TITLE
Added support for NUnit skipnontestassemblies

### PR DESCRIPTION
**Pull request by BlythMeister**
This is a recently new parameter in nunit console

### CODE REVIEW

**Comment by BlythMeister** [comment]
Once merged I can put this into fake 5 too (if not already there)

**Comment by BlythMeister** [comment]
Also, is the failing build my issue, or not.  Appveyor is passing, Travis is failing.

**Comment by matthid** [comment]
Yes please send another PR for the fake 5 code (this code-path will be available by merging the hotfix branch)

Yes travis is failing and I'd assume we won't fix it for hotfix branch. And mono-latest is green (only one of the jobs is red)

**Comment by BlythMeister** [comment]
So merge hotfix into master, fix up and pr?

**Comment by matthid** [comment]
Yes that works as well

**Comment by BlythMeister** [comment]
Since the fake 5 pr is merged, can this one be merged to 😂

**Comment by BlythMeister** [comment]
please

**Comment by matthid** [comment]
Just note that you can get the 5.0 package from staging already: https://www.myget.org/feed/fake-vsts/package/nuget/FAKE - It is probably removed soon (because we only keep 2 versions there) but you should be able to use that until another release is out.

The only disadvantage is that you get a couple of warnings to upgrade ;)

**Comment by matthid** [comment]
But you will get them soon anyway ;)

**Comment by BlythMeister** [comment]
Tbh, I'm going to be migrating to 5 anyways...so maybe we can just close this...

**Pull request closed without merging**
