### PR TITLE
Update Octokit module for GHE connections.

### PR DESCRIPTION
**Pull request by ianbattersby**
I can imagine there is a better or more idiomatic way of doing this, but for now this seems to work for me.

### CODE REVIEW

**Comment by forki** [comment]
I wonder if this can replace the existing client functions?

**Comment by ianbattersby** [comment]
True, could be an default parameter maybe (e.g. `(?url) token`)? Although I don't know (yet) if like C# all default arguments need to be on the end and if so it's a shame to lose url as the first param. I'll try and find some time to play.

**Comment by forki** [comment]
just let me know

**Comment by ianbattersby** [comment]
I'm learning optional arguments are only allowed on type members which seems a bit much. I was wondering if it might also be possible to have some kind of discriminated union type (?) as the last argument with you could match a `string` or `None` inside, but might small spikes haven't been too successful.

**Comment by forki** [comment]
I gueds it's best to merge it like that. But maybe you could convert GHE to GithubEnterprise or something

**Comment by forki** [comment]
thx

**Pull request merged**
