### PR TITLE
Pass instance of Diagnostics.Process for addOnStarted

### PR DESCRIPTION
**Pull request by maciej-izak**
### Description

Pass instance of Diagnostics.Process for created process for function used in addOnStarted
This feature was approved in [gitter](https://gitter.im/fsharp/FAKE?at=5df7c30bc6ce6027ebd1647d)

### CODE REVIEW

**Comment by matthid** [comment]
Ok, but question is if we should add a new method instead (as the current change is technically breaking all the following usages:
```fsharp
cp |> addOnStarted (fun () -> ())
```
And it is binary breaking (which probably kind of matters for the Process module as it is used everywhere)

**Comment by maciej-izak** [comment]
@matthid You are right. Maybe new method, for example `addOnProcessStarted` is better idea. What you think?

**Comment by matthid** [comment]
Yes or 'addOnStartedEx' with a record which we can extend in the future?

In any case thanks and congratulations to your first PR :)

**Comment by maciej-izak** [comment]
@matthid `addOnStartedEx` is ready. I have hope it is fine, but if in some point is not good enough let me know, this is my first PR in F# world ever :)

**Comment by matthid** [comment]
Thanks a lot!

**Pull request merged**
