### PR TITLE
Add tsconfig support for TypeScript compiler task

### PR DESCRIPTION
**Pull request by kylesonaty**
Referencing #1646

### CODE REVIEW

**Comment by matthid** [comment]
Very nice, do you think you could contribute the netcore migration for the `TypeScript` module?
There are some hints about how to do it in the contributors guide (https://fake.build/contributing.html).

Thank you!

**Comment by matthid** [comment]
Also to get this green you could rebase/merge latest master.

**Comment by kylesonaty** [comment]
I will give it a try.

**Comment by matthid** [comment]
Closing due to inactivity. Please feel motivated to open a new one based on the latest code. Obviously we would still love to see this as part of a new `Fake.JavaScript.TypeScript` module ;)

In the mean time we added documentation on how to migrate and add modules in the contribution docs.

**Pull request closed without merging**
