### PR TITLE
[WIP] [1933] Fix: nuget source handling is broken

### PR DESCRIPTION
**Pull request by 0x53A**
(I put this against ``release/rc`` because I based it on your changes, feel free to change to master or whatever)

### CODE REVIEW

**Comment by matthid** [comment]
Why WIP, this looks ready?

**Comment by 0x53A** [comment]
Because I haven't tested it. Are you confident in your CI? Otherwise I'll do a manual test tomorrow.

**Comment by 0x53A** [comment]
Or if you think the code looks good, pull it :)

**Comment by matthid** [comment]
Well I'm not so confident for every module (especially nuget) but we have a staging environment which will be deployed once I click merge ;)

**Comment by matthid** [comment]
thanks! Soon you can just test with staging ;)

**Pull request merged**
