### PR TITLE
General FAKE improvements

### PR DESCRIPTION
**Pull request by matthid**
See #1080. Sorry for all the problems produced by this.

At least I can now use the cleaned-up commits. I attached tests and fixes for the found issues at the end.

### CODE REVIEW

**Comment by matthid** [comment]
I think there is still one minor glitch when scripts write to stderr

**Comment by matthid** [comment]
I don't think scripts currently write into stderr so it is not that critical, should we just let them?
On the other hand some build servers fail when we write to stderr and we (and actually DO with this PR) handle that within FAKE by calling `traceError` but obviously this is not working when running the cached version. I think I'm adjusting this by redirecting stderr and stdout when calling the cached version as well.

**Comment by matthid** [comment]
Ok I think this should work now

**Comment by forki** [comment]
Ok cool. Let's try again.

**Pull request merged**
