### PR TITLE
Octotools tenant param

### PR DESCRIPTION
**Pull request by johanlasses**
Added a param in release options to support the new Tenant concept that have been added to Octopus.

### CODE REVIEW

**Comment by matthid** [comment]
Strictly speaking this needs a second PR to port the OctoTools to FAKE 5. We have documentation around that [here](http://fake.build/contributing.html#Porting-a-module-to-FAKE-5).

**Comment by johanlasses** [comment]
Yeah I saw that. I will see if I get the time for it.

**Comment by matthid** [comment]
ping @johanlasses

**Comment by johanlasses** [comment]
Sorry. I will try to get time and work on the FAKE 5 implementation.

**Comment by queil** [comment]
@johanlasses Is there any progress on OctoTools for FAKE 5? I thought I might help with that if necessary.

**Comment by matthid** [comment]
@queil Yes I think a new PR makes a lot of sense considering this hasn't changed for a while.

**Comment by matthid** [comment]
@queil note that you can submit early to let others know what you are doing and get intermediate feedback or help, just mark you pr as wip (work in progress). 
But that is up to you

**Comment by queil** [comment]
@matthid [Here](https://github.com/fsharp/FAKE/pull/2048) it is.

**Comment by matthid** [comment]
Ok I'm closing this then

**Pull request closed without merging**
