### PR TITLE
Use UTF-8 encoding for process output on Mono

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Fixes encoding issus on systems when encoding property is not set.

### CODE REVIEW

**Comment by forki** [comment]
good

@nosami @Yantrio is that that famous "chinese mono bug"?

**Comment by nosami** [comment]
Quite possibly :) If it is, then we have the same bug in Xamarin Studio somewhere :)

**Comment by forki** [comment]
Release in progress. Would love to hear if you can still reproduce Chinese
translation.
On Apr 10, 2016 19:17, "Jason Imison" <notifications@github.com> wrote:

Quite possibly :) If it is, then we have the same bug in Xamarin Studio
somewhere :)

—
You are receiving this because you modified the open/close state.

Reply to this email directly or view it on GitHub
<https://github.com/fsharp/FAKE/pull/1212#issuecomment-208019809>

**Comment by nosami** [comment]
Haven't seen it once since the chat in gitter the other day.

**Comment by Yantrio** [comment]
I'll give it a spin when I start work and let you know :+1:

**Comment by forki** [comment]
Looks like it broke others: https://github.com/fsharp/FAKE/issues/1213

Should I revert?

**Comment by forki** [comment]
Ok I reverted.

@juergenhoetzel I think the idea is good, but it seems we need to be more careful where to enable this.

/cc @kentcb

**Comment by juergenhoetzel** [comment]
> @nosami @Yantrio is that that famous "chinese mono bug"?

out

Output looks like chinese indeed.

**Comment by forki** [comment]
yes that' what @Yantrio and @nosami reported

**Comment by Yantrio** [comment]
Can I ask if you are getting it on osx only, or if it's on linux too @juergenhoetzel ?

**Comment by juergenhoetzel** [comment]
@Yantrio I use Arch Linux only (Mono 4.4.0.40 currently)

**Pull request merged**
