### PR TITLE
[Experimental] Rename FCS to avoid clashes (for #1096)

### PR DESCRIPTION
**Pull request by tpetricek**
This implements the solution (3) for  #1096

### CODE REVIEW

**Comment by tpetricek** [comment]
I added test script, which checks that another version of FCS can be loaded, but that's not actually run anywhere yet - so if we want to do this change, I'll need to turn this into a proper test first :)

**Comment by forki** [comment]
'packages\Mono.Cecil\lib\net45\Mono.Cecil.dll' missing

Seems you forgot to commit the deps and lock file

**Comment by tpetricek** [comment]
I fixed the paths and Travis now reports one failure (still working on AppVeyor):

    when running script
    » tracing functions should work (FAIL)

Do you have any hints on what this might mean?

Is there some easy way of running the FAKE tests with a debugger attached?

**Comment by matthid** [comment]
> Is there some easy way of running the FAKE tests with a debugger attached?

Visual Studio works for me :)

>Do you have any hints on what this might mean?

Error is here https://travis-ci.org/fsharp/FAKE/builds/103908100#L2181
Test is here: https://github.com/fsharp/FAKE/blob/master/src/test/Test.FAKECore/FSIHelperSpecs.cs#L214

But no I have no idea whats going on

**Comment by matthid** [comment]
It looks like FCS is searching for itself somehow? The script in the test is simply referencing `FakeLib.dll` and calling `traceFAKE`

**Comment by tpetricek** [comment]
As far as I can see: 

 - I don't get the test failure on Windows machine with older F# Compiler Service
 - Everything seems to pass on both CIs when using newer FCS

I tried searching F.C.S source code for places where it might try to reference itself using assembly name, but did not find anything. Though if we can get confirmation from @dsyme, that would help :)

**Comment by forki** [comment]
Let's try to build a new alpha

**Comment by forki** [comment]
OK it's released as alpha - how can we test it?

**Comment by forki** [comment]
I take that back. release failed because missing Fake.FSharp.Compiler.Service.dll.XML during docs build in FSharp.Formmating ;-)

**Comment by forki** [comment]
ok fixed that. let's see

**Comment by forki** [comment]
oK release succeeded. let's start dogfooding in FAKE and Paket.

**Comment by forki** [comment]
ok seems to work in Paket and FAKE itself

**Pull request merged**
